### ISSUE TITLE
数据库 dialect 能用除Mysql之外的吗？

### ISSUE THREAD

**Issue by gordonpro** [lisong/code-push-server#1]
比如 SQLite之类

**Comment by gordonpro** [comment]
Config.js中

**Comment by lisong** [comment]
sequelizejs本身是支持的， 但有的功能直接用的sql写的。不确定能否使用sqlite

**Comment by gordonpro** [comment]
居然还用了redis啊，够大。

**Comment by lisong** [comment]
redis有两个地方用了，1注册时用来存储注册码。2登陆时用来存储登陆错误次数，防止暴力破解。都是可配置的，建议还是开启。现在一般网站都会用到三个基本的软件，搜索引擎，缓存和数据库。考虑到elasticsearch大多数人不太熟悉，项目中暂时没有引入，因此还是使用了少量的连表查询。

**Comment by lisong** [comment]
服务器端数据库不建议用sqlite，他们都遵循sql标准，区别不大。
