### ISSUE TITLE
An unknown error occurred 

### ISSUE THREAD

**Issue by rokon338** [lisong/code-push-server#100]
android第一次部署版本，可以更新下来，然后紧接着又上传一个版本，这边能检测到更新，也能正常下载，但是无法安装，显示An unknown error occurred。然后后面每次点更新检测都显示是最细版本了。求解

**Comment by rokon338** [comment]
com.microsoft.codepush.react.CodePushInvalidUpdateException: The update contents failed the data integrity check.

**Comment by zhangyi5628** [comment]
同样的问题，不过我的是iOS第一次更新成功，然后后边的更新都不成功，提示：The update contents failed the data integrity check

**Comment by zhangyi5628** [comment]
@rokon338  请问你的问题解决了吗？

**Comment by lisong** [comment]
检查downloadUrl配置是否正确

**Comment by cuihonglei** [comment]
我今天用了多半天时间，解决了这个问题，原因是mac系统下，打包的目录中多了隐藏文件.DS_Store，导致hash校验失败，为什么第一次能成功呢，因为第一次下载不是diffUpdate，所以不做hash校验。
解决方法就是：每次打包前把./bundles目录整个删除或者把.DS_Store文件删除再打包就好了...
Android代码中CodePushUpdateManager.java中有这么一段代码，做hash校验的...
                        if (isDiffUpdate) {
                            CodePushUpdateUtils.verifyFolderHash(newUpdateFolderPath, newUpdateHash);
                        }

**Comment by Jinxiansen** [comment]
@wjj12138  cd 到 main.jsbundle 同级目录，移除 .DS_Store 即可。

**Comment by Jinxiansen** [comment]
补充下： 可以使用 `find . -name .DS_Store | xargs rm -rf` 递归删除当前及子目录所有此文件。

**Comment by yqz0203** [comment]
> 同样的问题，不过我的是iOS第一次更新成功，然后后边的更新都不成功，提示：The update contents failed the data integrity check

+1，ios有这个问题

**Comment by yqz0203** [comment]
> @wjj12138 cd 到 main.jsbundle 同级目录，移除 .DS_Store 即可。

之前已经上线过一次热更，后续的这样做还能补救吗？

**Comment by yqz0203** [comment]
@wjj12138 测试了 没有效果。。

**Comment by gaoneng102** [comment]
```shell
code-push release xx  xxx/CodePush '1.0.2' -d Staging --des 'v2版本热更新包'
```

’xxx/CodePush‘ 只要确保上传的根目录为CodePush，才能避免The update contents failed the data integrity check.错误
