### ISSUE TITLE
最低支持的android版本

### ISSUE THREAD

**Issue by Jam1zhu** [lisong/code-push-server#102]
最低支持的android版本是6.3？
```
cordova plugin add cordova-plugin-code-push@latest --save
```
安装插件提示，最低要求cordova-android版本是6.3，不然“cordova-plugin-file”会跳过安装，6.3也太高了吧？还是我设置的哪里有问题？求大佬指教

**Comment by lisong** [comment]
code-push-server 没有版本限制，主要依赖cordova-plugin-code-push客户端版本要求
