### ISSUE TITLE
encounter "[Error]  Could not parse response" after the deployment, but actually the deployment is successful.

### ISSUE THREAD

**Issue by zjx** [lisong/code-push-server#103]
`
 code-push release-react ...

Loading dependency graph, done.

bundle: start
bundle: finish
bundle: Writing bundle output to: /var/folders/88/f2g_m91j3ds38nqxk07c8d7c0000gn/T/CodePush/main.jsbundle
bundle: Copying 1 asset files
bundle: Done writing bundle output
bundle: Done copying assets

Releasing update contents to CodePush:

Upload progress:[==================================================] 100% 0.0s
[Error]  Could not parse response:
`

looks like the last error message is ignoring..

**Comment by zjx** [comment]
npm -v
5.5.1

node -v
v8.9.1

cordova -v
7.1.0

react-native -v
react-native-cli: 2.0.1

xcode 9.1

**Comment by ftb2010** [comment]
same

**Comment by hzcly98** [comment]
same to you ~~

**Comment by hzcly98** [comment]
can somebody help us?

**Comment by yechunxi** [comment]
Any solution to this problem?

**Comment by readthecodes** [comment]
same problem, any solution?

**Comment by kele1990** [comment]
same

**Comment by jeoy** [comment]
@hzcly98  @yechunxi  @readthecodes  @kele1990  @zjx  check this solution 
https://github.com/jeoy/code-push-server/commit/caa5d0a6e26e1b7bbdd9ab80476a7437c934805b

**Comment by Ruanyang2015** [comment]
me too

**Comment by stlemon** [comment]
same

**Comment by iRockyZhou** [comment]
same
