### ISSUE TITLE
应用安装了，但总数一直为0

### ISSUE THREAD

**Issue by Better-Jiao** [lisong/code-push-server#104]
已经在config.xml中配置了 
```
<preference name="CodePushDeploymentKey" value="WuwDcPmjzopOVvQh1H07Lo98dHQ94ksvOXqog" /> //生成的key
        <preference name="CodePushServerUrl" value="http://192.168.31.61:3000/" /> //服务器地址，
```
codepush也已经安装
```
code-push 1.8.0-beta "CodePushAcquisition"
cordova-plugin-code-push 1.8.2-beta "CodePush"
```
同时app报An error occured while checking for updates错误

**Comment by lisong** [comment]
检查code-push-server downloadUrl配置是否正确

**Comment by Better-Jiao** [comment]
这是我config.js的配置
```
local: {
    // Binary files storage dir, Do not use tmpdir and it's public download dir.
    storageDir: process.env.STORAGE_DIR || "/Users/tablee/workspaces/storage",
    // Binary files download host address which Code Push Server listen to. the files storage in storageDir.
    downloadUrl: process.env.LOCAL_DOWNLOAD_URL || "http://192.168.0.150:3000/download",
    // public static download spacename.
    public: process.env.PUBLIC || '/download'
  }
```
/Users/tablee/workspaces/storage这个文件里面也有数据。
同时我发现手机上发送的请求updateCheck的method是options，没有返回值，同样的请求在浏览器是get，有返回值。

**Comment by jacintoface** [comment]
请问怎么解决的呢

**Comment by hooliy** [comment]
@Better-Jiao 你好！请问如果解决 OPTIONS 请求无返回结果的问题呢？

**Comment by hooliy** [comment]
@jacintoface 

`if ($request_method = 'OPTIONS') {
    add_header 'Access-Control-Allow-Credentials' true;
    add_header 'Access-Control-Allow-Origin' "$http_origin";
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
    add_header 'Access-Control-Allow-Headers' 'x-codepush-plugin-name,x-codepush-plugin-version,x-codepush-sdk-version,DNT,X-Custom$
    add_header 'Access-Control-Max-Age' 1728000;
    add_header 'Content-Type' 'text/plain; charset=utf-8';
    add_header 'Content-Length' 0; return 204;
}
                        proxy_pass http://localhost:3000/;`


在Nginx里添加 **'x-codepush-plugin-name,x-codepush-plugin-version,x-codepush-sdk-version,**
