### ISSUE TITLE
windows上如何配置，windows上能否修改默认端口号，不用默认3000端口

### ISSUE THREAD

**Issue by ftb2010** [lisong/code-push-server#106]
windows上如何配置，windows上能否修改默认端口号，不用默认3000端口

**Comment by jishuke** [comment]
在 /bin/www 文件 修改下面 默认为 3000  修改为 3890
/**
 * Get port from environment and store in Express.
 */

var port = normalizePort(process.env.PORT || '3890');
log.debug('port ' + port);

**Comment by lisong** [comment]
可以设置环境变量
