### ISSUE TITLE
app to date

### ISSUE THREAD

**Issue by plimerence** [lisong/code-push-server#108]
1.我先提交一个bundle包版本1.0.1OK  点击检测可以更新然后更新显示正常，然后我改变代码  继续打包并且发布1.0.2这时候点击app检测 提示app to date PS:是bug 还是我使用姿势不对 ？ 求教正确姿势

2.我修改xcode 里面的Bundle versions string, short 以及Build会造成什么影响。
3.我看downloadURL 指向的是这里（图片）,
![snip20171211_3](https://user-images.githubusercontent.com/13290201/33825720-89a8c714-de9d-11e7-8f63-ea13e9abe73e.png)
这个是差异包吗？感觉还是有些大

**Comment by plimerence** [comment]
找到app to data的原因了 code-push release Trip ./ios/bundle/index.ios.jsbundle 1.0.0   最后这个<targetBinaryVersion>指的是APP的 version所以如果一直在1.0.0上推更新 就一直1.0.0就好了

**Comment by jacintoface** [comment]
请问下downloadUrl 到底是指向的啊, 我一直显示appUpDate,找到了在client-manager里models.DeploymentsVersions.findOne的deploymentsVersions返回为Null

**Comment by MrPluto** [comment]
打包命令中的 appversion 并不是指热更新包的 patch版本，而是你指定那一个版本的应用需要更新
例如 iOS 打包时 version 是 1.0.0， 那么以后每次你想在这个版本上应用热更新，code-push 时的 appversion 指的就是 1.0.0 
😢
