### ISSUE TITLE
npm install  安装报错

### ISSUE THREAD

**Issue by wuxushun** [lisong/code-push-server#11]
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/root/.nvm/versions/node/v6.9.1/bin/node" "/root/.nvm/versions/node/v6.9.1/bin/npm" "install" "code-push-server" "-g"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/app/code-push-server/npm-debug.log
npm ERR! code 1

**Comment by lisong** [comment]
`npm -v`
`node -v`
npm node 版本分别是？

**Comment by wuxushun** [comment]
npm ERR! node v6.9.1
npm ERR! npm v3.10.8        
貌似bcrypt安装不上

**Comment by lisong** [comment]
升级npm后还有问题没？

**Comment by lisong** [comment]
`npm install npm@next -g`

**Comment by wuxushun** [comment]
还是不行，  我网上搜了  bcrypt编译  很多遇到问题了  请问你是windows环境 还是linux环境？

**Comment by lisong** [comment]
windows linux集成测试都是可以的，集成测试node版本测试到6.2，https://travis-ci.org/lisong/code-push-server

**Comment by lisong** [comment]
readme中的图标可以看到window node版本到6.2是没有问题的，待会我加到6.9看有没有这种问题

**Comment by wuxushun** [comment]
@lisong  感谢   我一会儿也试试6.2可否成功

**Comment by wuxushun** [comment]
使用6.2还是不行，   系统环境用的 ubuntu14   gcc pyhton  都已经安装了  能否告知哪个JS文件使用了这个库 我把这个库替换了

**Comment by wuxushun** [comment]
是环境问题  我换了个环境同样的node版本能编译成功了
