### ISSUE TITLE
http://192.168.8.139:3000/updateCheck 我得到的数据 是空  

### ISSUE THREAD

**Issue by jishuke** [lisong/code-push-server#110]
本地的文件夹是有 文件的 热更新版本号2.2.1  
{
	"updateInfo": {
		"downloadURL": "",
		"downloadUrl": "",
		"description": "",
		"isAvailable": false,
		"isMandatory": false,
		"appVersion": "2.2.0",
		"packageHash": "",
		"label": "",
		"packageSize": 0,
		"updateAppVersion": false,
		"shouldRunBinaryVersion": false
	}
}

怎么办呢

**Comment by jacintoface** [comment]
请问下怎么解决的呢
