### ISSUE TITLE
codepush完全没法操作了

### ISSUE THREAD

**Issue by kele1990** [lisong/code-push-server#111]
我按照教程部署了code-push-server，一切良好，某一天，我的部署服务器被别人删掉了数据库，停掉了服务，无法恢复，我又重新选择一台服务器部署，部署好了，问题来了：
我使用code-push的电脑无法执行code-push logout命令，也无法重新登录，提示已经登录过了，我卸载了code-push-cli，重新安装，依然提示已登录过，求救！！！
@lisong

**Comment by lisong** [comment]
https://github.com/lisong/code-push-server/issues/53

**Comment by kele1990** [comment]
十分感谢
