### ISSUE TITLE
upload error

### ISSUE THREAD

**Issue by coloz** [lisong/code-push-server#116]
Upload progress:[===============================                   ] 63% 0.3s[Error]  upload error

这会是什么原因导致的呢？用的七牛，已确定key正确

**Comment by lisong** [comment]
有后台日志报错没？是不是用仓库最新master代码

**Comment by coloz** [comment]
最新代码，后台没有报错，每次都是上传错误，且每次传的百分比都不一样

**Comment by coloz** [comment]
七牛的downloadurl是指七牛绑定的域名吗？

**Comment by lisong** [comment]
是七牛外网地址，能够访问到你上传的包

**Comment by zc-Mukden** [comment]
上传文件的大小限制吧，我把图片资源删了，又成功了。但找不到在哪里修改它的限制大小，求助啊！

**Comment by qq444716720** [comment]
@zc-Mukden  我也出现 upload error了
请问你解决了吗

**Comment by zc-Mukden** [comment]
@qq444716720 
(1) 升级formidable至1.2.1(不低于1.1.1)
vi /codepush/code-push-serverpackage.json

 "debug": "^2.6.8",
     "express": "^4.14.0",
     "extract-zip": "^1.6.0",
     "formidable": "^1.0.17",修改为："formidable": "^1.2.1",
     "fs-extra": "^3.0.1",
     "helmet": "^3.1.0",
     "i18n": "^0.8.3",

删除目录：
cd /codepush/code-push-server
mv node_modules node_modulesback

更新：
cd /codepush/code-push-server
npm i
(2) 修改core/services/package-manager.js的formidable增加form.maxFilesSize = 200  1024  1024;
  log.debug('parseReqFile');
   return new Promise((resolve, reject) => {
     var form = new formidable.IncomingForm();
     form.maxFilesSize = 200  1024  1024;   ###添加这一行
     form.parse(req, (err, fields, files) => {
       if (err) {
         log.debug('parseReqFile:', err);

**Comment by qq444716720** [comment]
@zc-Mukden  在你回复之前我刚刚已经解决了，你回复好看啊， 谢谢你哈

**Comment by qq444716720** [comment]
@zc-Mukden 好快。 字打错了，哈哈
