### ISSUE TITLE
如何指定 config.test.js

### ISSUE THREAD

**Issue by L-Jovi** [lisong/code-push-server#118]
作者你好，首先感谢你的项目。

看到 package.json 中有 dev 的子命令，实际启动 `npm run dev` 后发现依然加载了 config.js 生产环境的配置文件，而且当我修改 storageType 为 local 后依然会去连接 mysql

我尝试了使用环境变量 CONFIG_FILE 和 NODE_ENV 但是服务依然会连接 mysql，我如何指定读 config.test.js 中通过本地的方式启动服务呢？

感谢

**Comment by lisong** [comment]
config.test.js只是集成测试用例用到的配置，直接使用config.js，里面有变量区分不同的环境

**Comment by L-Jovi** [comment]
感谢回复
