### ISSUE TITLE
ios热更新是否需要https访问

### ISSUE THREAD

**Issue by china-chen** [lisong/code-push-server#119]
在Info.plist中添加CodePushDeploymentKey和CodePushServerURL后ios端热更新没起作用，android端可以，是不是和http的访问地址有关？

**Comment by lisong** [comment]
可以使用nginx做loadbalance，HTTPS配置nginx上很好支持

**Comment by jacintoface** [comment]
请问下你android端是怎么做的啊，我怎么每次请求都返回是最新版本啊，但是我deployment history上是有害没有更新的版本的

**Comment by zchlon** [comment]
Info.plist需要设置NSAppTransportSecurity，才能使用http接口。另外你的CodePushDeploymentKey是设置多个DeploymentKey的配置（比如有staging和release两种的），可以参考官网设置方法，对准相应英文字母来设置就行了。
