### ISSUE TITLE
集成碰到的两个问题，帮忙看看，谢谢

### ISSUE THREAD

**Issue by might8magic** [lisong/code-push-server#12]
1.执行code-push release-react CodePushDemo-ios ios -d Production或在App点更新，控制台出现：
GET /download/FiF3MP8tbkXx_dkU0OFIE3beImwE 404 0.778 ms - 1987
Error: Not Found
    at /usr/local/lib/node_modules/code-push-server/app.js:69:13
    ...
app界面无变化

2.在mac下我用http://localhost:3000和http://127.0.0.1:3000都可以访问，用局域网ip却不行，我没有改host文件，也没有在浏览器设代理

**Comment by might8magic** [comment]
重启code-push服务第一个问题好了

**Comment by lisong** [comment]
默认监听的地址127.0.0.1，端口3000。请参照readme.md中如何配置监听端口和指定自己的配置文件。配置文件的时候要根据自己的环境检查，readme中有详细描述

**Comment by lisong** [comment]
局域网IP访问启动时监听局域网IP

**Comment by lisong** [comment]
第一个问题是配置文件中的目录需要修改成你自己的目录

**Comment by might8magic** [comment]
android模拟器搞了好久，没执行adb reverse，另外这命令android5.0才支持，我用4.x的模拟器.. 都搞定后测试挺稳定的。http://192.168.1.100:3000/这样的路径不能访问是不是node的设置不对？tomcat用IP都是好的

**Comment by might8magic** [comment]
另外，code-push的热更新是增量还是全量的？

**Comment by lisong** [comment]
是增量更新，tomcat默认监听的是 *

**Comment by lisong** [comment]
ok 现在默认监听的IP也是 0.0.0.0 路

**Comment by NoPPT** [comment]
@lisong  
你好，我有两个问题能帮忙看下吗？
1. 启动服务./bin/www会有一个终端，如果关掉的话服务也关闭了，怎么能让服务后台运行？
2. 怎么更改mysql的端口号？
多谢

**Comment by lisong** [comment]
1.使用pm2管理 readme中有提到
2.可以修改config/config.js配置文件, 使用pm2中有提到。配置文件中的一些配置要根据你实际情况配置
