### ISSUE TITLE
执行 node ./bin/www 失败

### ISSUE THREAD

**Issue by shuijinliuxi** [lisong/code-push-server#120]
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13
internal/crypto/hash.js:53
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'data',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView
    at Hash.update (internal/crypto/hash.js:53:11)

**Comment by lisong** [comment]
是否更新了code-push-server没有重新运行 `npm install`
