### ISSUE TITLE
upload error

### ISSUE THREAD

**Issue by wwx193433** [lisong/code-push-server#123]
Upload progress:[============================================      ] 87% 0.0s[Error]  upload error

**Comment by wwx193433** [comment]
我是完全按照教程上面的步骤，试了好多次都是这个错误。。
![wechatimg51](https://user-images.githubusercontent.com/28697411/38085792-6cedf46e-3384-11e8-9cf6-c20cd6b4bfd2.jpeg)

**Comment by zc-Mukden** [comment]
我觉得是上传限制了文件的大小，因为我删了些就可以上传成功。。。。但我不知道在哪里配置它大小！有知道的麻烦告知一声！

**Comment by lisong** [comment]
更新到最新代码还有这种情况发生么？
