### ISSUE TITLE
upload error

### ISSUE THREAD

**Issue by zc-Mukden** [lisong/code-push-server#126]
D:\WebStromProject\LotteryTwoNine>code-push release  Lottery-android   ./bundles/    1.0.0    --deploymentName  Staging     --description   "v1"     --m
andatory true
Upload progress:[==================================================] 100% 0.0s
[Error]  upload error

My own server, using code-push-server

**Comment by zc-Mukden** [comment]
我删除了一部分图片。就能上传成功，是哪里限制了上传文件的大小吗？？？但是我找不到怎么修改它！求助啊，加急。。。。。

**Comment by lisong** [comment]
最新master已经解决
