### ISSUE TITLE
发布到Windows服务器，app更新时404

### ISSUE THREAD

**Issue by qq444716720** [lisong/code-push-server#127]
![image](https://user-images.githubusercontent.com/22407004/38507700-c562a3c8-3c4f-11e8-9ed6-44a2a8407e75.png)

**Comment by BigCoding** [comment]
看下code-push-server工程config.js中的downloadUrl配置是否正确，有可能是ip不对

**Comment by 232824787** [comment]
![image](https://user-images.githubusercontent.com/17864667/43620496-a6a4cd56-9705-11e8-9584-b4e23ffb8b88.png)

下载地址 
 /download/fg/FgtjGMBr5DmpMuyhClRibl75EMfX
[2018-08-03T10:08:45.888] [ERROR] cps:app - { NotFoundError: Not Found
    at C:\Users\****\AppData\Roaming\npm\node_modules\code-push-server\app.js:87:15
    at Layer.handle [as handle_request] (C:\Users\******\AppData\Roaming\npm\node_modules\code-push-server\node_modules\express\l
ib\router\layer.js:95:5)
![image](https://user-images.githubusercontent.com/17864667/43620556-dc209816-9705-11e8-88e4-5a340b9f6900.png)


也是下载不了

**Comment by Helry** [comment]
我也遇到了这个问题，请问我路径一样的为什么也是下载不了

**Comment by jishuke** [comment]
你好 你怎么解决的呀
