### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by L-Jovi** [lisong/code-push-server#13]
想问下这是自己搭建私有的 code push server 嘛  官方文档貌似只找到 sdk 和 cli 的集成方法

有哪里提供官方的搭建 code push server 服务的文档么

感谢

**Comment by lisong** [comment]
微软官方没有，这个仓库readme有详细教你搭建code push server的方法

**Comment by L-Jovi** [comment]
@lisong  感谢回复  这个很赞!
