### ISSUE TITLE
“而中国的android市场都必须关闭更新弹框”什么意思

### ISSUE THREAD

**Issue by Riant** [lisong/code-push-server#134]
> （苹果）规定不能弹框提示用户更新，影响用户体验。 而Google Play恰好相反，必须弹框告知用户更新。然而中国的android市场都必须关闭更新弹框，否则会……

其中必须关闭更新弹框，是和苹果的不能提示用户更新 一个意思，还是指必须弹框告知用户更新，但是在用户确认更新之后，即进行静默更新，不提示更新进度啊？

谢谢。

**Comment by lisong** [comment]
中国的android市场只能是用静默更新, Google Play 不能采用静默更新
