### ISSUE TITLE
Any problems to concern, if I use S3?

### ISSUE THREAD

**Issue by devhyunjae** [lisong/code-push-server#14]
Want to use `S3`, instead of `qiniu`

https://github.com/lisong/code-push-server/blob/master/core/utils/common.js#L158

I am planning to replace this part to s3upload.

Seems like there is no problem, but it should be better asking to the owner :)

**Comment by lisong** [comment]
you can add another option like qiniu，not instead，then ask a pull request for others who need use s3 two. thanks.

**Comment by devhyunjae** [comment]
OK, I'll  try to make an option for `storageType: "s3"`

**Comment by HFYEH** [comment]
@devhyunjae @lisong :

I use S3, when I code-push, it shows the error message below. I found I don't know where to put my credential in config.js file for S3, would you help me? Thank you very much!

![image](https://cloud.githubusercontent.com/assets/7251421/23197154/3c2f929a-f8f9-11e6-85c9-8d837b534838.png)

**Comment by lisong** [comment]
if you are use `npm i code-push-server -g`, it suggest download the [config file](https://github.com/lisong/code-push-server/blob/master/config/config.js) ,then use `CONFIG_FILE=/path/to/config.js  code-push-server`, startup the server. if you use source code then config in config/config.js

**Comment by HFYEH** [comment]
I use source code and I do edit my config.js, it looks like this

![image](https://cloud.githubusercontent.com/assets/7251421/23197702/10e9f72a-f8fd-11e6-932e-e1f60060d1a0.png)

![image](https://cloud.githubusercontent.com/assets/7251421/23197720/2c9b5ef0-f8fd-11e6-8b84-df641ae09fbd.png)

I don't know where could I put my s3 id and key.

**Comment by devhyunjae** [comment]
@HFYEH 
You need to setup AWS credentials. These are not related to `code-push-server config`
The easiest way is to set these two as env variable.

```
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
```

http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-environment.html

**Comment by lisong** [comment]
@devhyunjae maybe it more better set in config files.

**Comment by HFYEH** [comment]
Thank you both.

I export it as environment variable and restart server.

When I use pm2, I still get same error message.

But if I use `bin/www`, it woked. Seems pm2 cannot read my environment variable.

**Comment by lisong** [comment]
[process.json](https://github.com/lisong/code-push-server/blob/master/docs/process.json)，you can set env in pm2 file
