### ISSUE TITLE
why  Release time always is 8 hours ago?

### ISSUE THREAD

**Issue by pczhang123** [lisong/code-push-server#140]
Update  Metadata Release time  is 8 hours  ago, How can I modify it?

**Comment by pczhang123** [comment]
时区问题？

**Comment by lisong** [comment]
应该是code-push客户端显示时区问题

**Comment by jamninetyfive** [comment]
@lisong  怎么修改？

**Comment by tututututututu** [comment]
我也遇到这个问题  请问有解决办法吗

**Comment by zyuyou** [comment]
@tututututututu 这个是服务端问题, sequelize库有bug, package-lock.json里面的版本没有更新, 更新一下就好
