### ISSUE TITLE
执行更新出现TypeError: Network request failed

### ISSUE THREAD

**Issue by wuge123** [lisong/code-push-server#142]
wugedeMacBook-Air:dust wuge$ code-push release dust ./android/bundles/main.jsbundle 1.0.1 --deploymentName Production --description "我是新包，很新的那种" --mandatory true
Upload progress:[==================================================] 100% 0.0s
Successfully released an update containing the "./android/bundles/main.jsbundle" file to the "Production" deployment of the "dust" app.
发布是OK的，然后我前台调用CodePush.checkForUpdate出现TypeError: Network request failed
调用getUpdateMetadata返回是null,我漏了什么吗

**Comment by lisong** [comment]
建议使用 code-push release-react code-push-server不支持单个文件上传
