### ISSUE TITLE
更新出现An unknown error occurred

### ISSUE THREAD

**Issue by wuge123** [lisong/code-push-server#143]
[CodePush] Checking for update.
 [CodePush] Reporting binary update (1.0.4)
[CodePush] An unknown error occurred.
[CodePush] Network request failed
[CodePush] Report status failed: {"appVersion":"1.0.4"}

**Comment by lisong** [comment]
应该是config中downloadUrl配置错误，将 127.0.0.1 改成公网ip或者域名

**Comment by Foveluy** [comment]
@lisong 已经改了，然而并没有用，这个是出现在 release 版本的安卓里面，但是 debug 版本是好的

**Comment by upcwangying** [comment]
@Foveluy 你解决了吗？我也遇到了同样的问题
