### ISSUE TITLE
使用 code-push login --accessKey <accessKey> 登录报错！

### ISSUE THREAD

**Issue by zhaoshuoer** [lisong/code-push-server#146]
作者您好：
我在登录的状态下
```code-push login http://127.0.0.1:3000```

使用 ```code-push access-key add "My Key"``` 创建了一个密钥

并且使用```code-push access-key list```是可以看到新创建的密钥

当我退出登录，尝试使用生成的密钥登录时
```code-push login --accessKey <accessKey>```

报错了
```[Error] Invalid access key.```

我是从2018年7月16号 从 ```git://github.com/lisong/code-push-server.git``` 直接clone下来的！
除了该功能报错外目前能正常使用，但是我需要使用Jenkins自动发布，希望您能帮帮我！谢谢！

**Comment by zhaoshuoer** [comment]
我临时解决了，在数据库中的user_tokens表中手动把一个已存在的token的is_session字段改为了0，就可以了！

**Comment by lisong** [comment]
使用命令`code-push logout` 退出，会将当前accessKey失效掉。重新登录获取新的accessKey即可解决
