### ISSUE TITLE
code-push-server 如何查询某一个版本的补丁总数

### ISSUE THREAD

**Issue by renjinlong** [lisong/code-push-server#153]
目前deployments表里label_id 表示的是某个项目环境的补丁总个数，有方法可以做到某个版本的补丁总数吗？例如1.0.3这个版本的补丁个数？

**Comment by lisong** [comment]
暂时没有接口支持查看，可以根据数据库中的数据统计

**Comment by renjinlong** [comment]
还是自己加了一个字段，统计某个版本的补丁总数，谢谢，回复
