### ISSUE TITLE
网络请求成功,但是不能下载!!!

### ISSUE THREAD

**Issue by SPingels** [lisong/code-push-server#154]
[2018-08-22T20:24:12.014] [INFO] http - ::ffff:192.168.1.115 - - "GET /updateChe
ck?deploymentKey=JR25WDROwNsWZLolB5GiIAWcK43I4ksvOXqog&appVersion=1.0.0&packageH
ash=&isCompanion=&label=&clientUniqueId=16daaab309df2bc0 HTTP/1.1" 200 449 "" "o
khttp/3.6.0"

疑问:日志中的IP地址是192.168.1.115,但是我的主机IP是192.168.1.117.在code-push-server和自己的项目中均没有搜到192.168.1.115的IP.

**Comment by lisong** [comment]
浏览器中访问，查看返回的downloadUrl是否配置正确

**Comment by SPingels** [comment]
使用地址:http://127.0.0.1:3000/updateCheck?deploymentKey=JR25WDROwNsWZLolB5GiIAWcK43I4ksvOXqog&appVersion=1.0.0&packageHash=&isCompanion=&label=&clientUniqueId=16daaab309df2bc0可以请求到json数据,通过请求里面的downloadURL,也能下载资源.
下图:
![image](https://user-images.githubusercontent.com/11756371/44500626-191a0c00-a6bc-11e8-8f32-ad6974aa49d7.png)
但是现在仍不知道为什么请求的IP地址是192.168.1.115!!!

**Comment by lisong** [comment]
你是在模拟器里面运行的？

**Comment by SPingels** [comment]
不是!打包的apk在手机上测试的~是在同一个局域网下!

**Comment by SPingels** [comment]
我在MainApplication.java中做了如下处理:
```
    @Override
        protected List<ReactPackage> getPackages() {
            return Arrays.<ReactPackage>asList(
                    ...
                    new CodePush(
                            "JR25WDROwNsWZLolB5GiIAWcK43I4ksvOXqog",
                            MainApplication.this,
                            BuildConfig.DEBUG,
                            "http://192.168.1.117:3000"//添加了serverUrl
                    ),
                    ...
            );
        }
```
不会是serverUrl引起的吧?但是我这里的IP地址没有给错呀!

**Comment by SPingels** [comment]
是的!!!能更新了!!!192.168.1.115是手机的IP地址!!!感谢!!!
