### ISSUE TITLE
关于七牛云的配置问题

### ISSUE THREAD

**Issue by lhh-sofy** [lisong/code-push-server#159]
你好. 使用七牛云作为存储空间时候，我的downloadUrl直接写的 域名+‘/download’,但是我上传到七牛上 的文件路径居然是 域名当前的文件路径  。该如何配置，才能到download/ “文件夹”下面。。。

**Comment by lisong** [comment]
七牛云等相关云存储只需要配置域名，download目录只有本地local存储才需要

**Comment by lhh-sofy** [comment]
> 七牛云等相关云存储只需要配置域名，download目录只有本地local存储才需要我
我修改了一下代码，加了一个prefix,这样可以把文件上传到相应到prefix中..

**Comment by lisong** [comment]
OK

**Comment by LiuYuHangNB** [comment]
你好,我能上传到七牛,但是检查不到更新无法更新,能请教下你的七牛是怎么配置的么?
