### ISSUE TITLE
checkUpdate检测到有更新，但是下载包是报An unknown error occurred

### ISSUE THREAD

**Issue by ChuxuaNmuxu** [lisong/code-push-server#162]
#### 当前的问题：
1. 检查到有更新，点击press for dialog-driven sync有提示是否继续
* ![image](https://user-images.githubusercontent.com/18677300/47769365-9f834780-dd16-11e8-9868-e04356dc679d.png)
2. 点击继续之后报 An unknown error occurred
3. 调试发现react-native-code-push下的package-mixins.js,执行到
![image](https://user-images.githubusercontent.com/18677300/47769672-9d6db880-dd17-11e8-9137-afbf92edc26b.png)
就执行不下去了，这里是用的微软的codepush下载js包的方法，应该是这里在下载代码的时候报错了，
4. https://127.0.0.1:3000/updateCheck?deploymentKey=YOUR_KEY&appVersion=1.0.0&packageHash=&isCompanion=false&label=&clientUniqueId=8A622DF0-D118-4B2D-915B-D9FF0F474EA8  
返回  
{"updateInfo":{"downloadURL":"http://127.0.0.1:3000/download/fh/FhvTiI6nm7NKCeJjgrBS0NW-jIHj","downloadUrl":"http://127.0.0.1:3000/download/fh/FhvTiI6nm7NKCeJjgrBS0NW-jIHj","description":"测试热更新登陆--","isAvailable":true,"isMandatory":true,"appVersion":"1.0.9","packageHash":"a2df57da7e58fc01df29f3d6a8424e5ce3181162258d378856be52b35acb23e4","label":"v17","packageSize":908481,"updateAppVersion":false,"shouldRunBinaryVersion":false}}
5. http://127.0.0.1:3000/download/fh/FhvTiI6nm7NKCeJjgrBS0NW-jIHj 可以正常下载文件，解压后如下
![image](https://user-images.githubusercontent.com/18677300/47769734-e4f44480-dd17-11e8-8a48-f30929081a98.png)
#### 预期
可以下载更新的文件包并安装
#### 当前的环境
* react-native: 0.55.4
* react-native-code-push： 5.4.2

**Comment by ChuxuaNmuxu** [comment]
解决了，打扰了，打扰了~

**Comment by ninechung** [comment]
@ChuxuaNmuxu 怎么解决的？怎么不说一下呢？

**Comment by ChuxuaNmuxu** [comment]
是这样，我用的是本地code-push服务，按照教程配置local.downloadUrl
![image](https://user-images.githubusercontent.com/18677300/48876689-6d0ecb00-ee3a-11e8-8af7-33aef2c91251.png)
调试代码是发现从localhost下载不到更新的包，改成本机的ip就行了
另外：docker镜像，我在ecs上构建后访问不了mysql，将网络配置部分去掉就可以了，应该是docker的网络配置问题，望知悉

**Comment by bean-sprouts** [comment]
感谢大佬

**Comment by QAZDER** [comment]
你好，最近集成的时候碰到了An unknown error occurred 的问题。应该也是无法获取打包完的js文件。
本地的下载地址已经改成域名的形式了，不过还是不行
想问一下，docker配置的时候，需要更改默认的挂载目录吗？不知道和Mac系统有没有关系
@ChuxuaNmuxu
