### ISSUE TITLE
更新不了

### ISSUE THREAD

**Issue by wangfugui123** [lisong/code-push-server#163]
搭建了server，也发布了，能看到。  但是客户端就是更新不了，一直是最新的；但服务端已经有版本要更新的

**Comment by lisong** [comment]
能给些详细信息描述么？

**Comment by Cui-y** [comment]
@lisong  后端在阿里云上搭建code-push server ，账号密码用的默认的 您创建的那个，我提交的记录上，Release By 您的邮箱账户，具体截图如下:
![image](https://user-images.githubusercontent.com/21211512/47965364-54a06180-e081-11e8-9043-90ab7370cc32.png)

**Comment by Cui-y** [comment]
@lisong  后端在阿里云上搭建code-push server ，账号密码用的默认的 您创建的那个，我提交的记录上，Release By 您的邮箱账户，具体截图如下:
![image](https://user-images.githubusercontent.com/21211512/47965375-7568b700-e081-11e8-96fb-717fe6c802bc.png)

**Comment by Cui-y** [comment]
更新推送命令也是参考demo下的：
code-push release-cordova youjiajinke-android android -d Production 
截图如下
![image](https://user-images.githubusercontent.com/21211512/47965393-acd76380-e081-11e8-8f96-d962ccc0cacf.png)

**Comment by lisong** [comment]
`code-push history --format json` 查看一下downloadurl，直接浏览器访问是否能访问

**Comment by wlxscn** [comment]
![image](https://user-images.githubusercontent.com/12622564/49340115-78ea6080-f676-11e8-9fad-82f5dbf97caf.png)

请问一下code-push的更新策略，我看源代码里只能查到当前app版本对应的package，所以上传新的package之后，app并不会检测到有新的package。我现在会手动更改数据库当前app版本对应的package版本，这样的才会更新

**Comment by wlxscn** [comment]
我这边也是更新不了
