### ISSUE TITLE
初始化账号的问题

### ISSUE THREAD

**Issue by L-Jovi** [lisong/code-push-server#17]
你好  首先感谢你的这个项目

这里想问几个关于 codepush 的问题

1. 我看到你初始化设置了 账号 `admin` 和 密码 `123456`  我目前已经通过 __code-push-cli__ 成功的 login 并且生成了我本地的 session config
我的问题是这个初始的账号密码是否可以使用 code-push-cli 更换

2. code-push-cli 是否只能记忆单次会话
  我之前是使用微软官方的公有云   在登出了之后我指定了本地 `http://localhost:3000` 作为参数生成了新的 config
  这是不是意味着以后我想再使用微软之前生成的账号  就需要再次先 logout 后重新 login 微软公有云才有效?

3. 如果上述条目 2 成立  我在第一次指定了 `code-push-cli login http://localhost:3000` 之后的所有后续操作  比如 `code-push app add <MyApp>` 等等  是不是都不再需要指定本地的 url 参数了  会直接发送到 http://localhost:3000 的服务?

感谢回复

致意

**Comment by lisong** [comment]
1. admin密码不能通过code-push-cli更换，可以是code-push-web更换，或者直接curl方式更改，待会我把curl命令发你。
2. code-push-cli登陆后的session存储在 ~/.code-push.config 文件中，微软code-push云端和自己搭建的code-push没有关联性，所以登陆不共用。
3.  正如你的理解，当你登陆指定url时，登陆后的操作发送的请求都发送到指定的url服务上。

**Comment by lisong** [comment]
`$ curl -X PATCH -H "Authorization: Bearer mytoken" -d '{"oldPassword":"123456","newPassword":"654321"} http://127.0.0.1:3000/users/password`

**Comment by L-Jovi** [comment]
@lisong  感谢回复  再次感谢你对这个项目的贡献 :)

**Comment by L-Jovi** [comment]
@lisong  你好

1. 在调用修改密码 `/password` 接口操作时  需要授权  想问下请求的头信息中 `Authorization: ` 中填写的是什么  我尝试了 `http://localhost:3000/auth/login` 返回的 token 没有效果

2. 想问下 `config.js` 中 `loginSecret` 在哪里使用  还没有很理解这个配置的意义

感谢

**Comment by lisong** [comment]
code-push 命令行生成的access key

**Comment by lisong** [comment]
要理解loginSecret 可以参考 json web token 的实现方式，google jwt

**Comment by L-Jovi** [comment]
@lisong  感谢回复 :)

**Comment by L-Jovi** [comment]
@lisong 抱歉再次打扰

成功的添加了项目并使用 `code-push release-react MyProject-ios ios -m` 后看到 server 目录下已经存储了推送的资源  但是发现返回的信息有一行报错  

    [Error]  ER_DATA_TOO_LONG: Data too long for column 'description' at row 1

去官方文档没找到原因  请问下是 `code-push` 自己的原因嘛  如何解决呢

非常感谢你的耐心

致意

**Comment by lisong** [comment]
--description 后面的字符太长了吧，数据库只设置了100个字符

**Comment by lisong** [comment]
`ALTER TABLE `packages` CHANGE `description` `description` VARCHAR(500)  CHARACTER SET utf8  COLLATE utf8_general_ci  NOT NULL  DEFAULT '';
`

**Comment by L-Jovi** [comment]
@lisong  感谢回复

想问下这个修改动作可以通过 orm 层实现嘛

我看到你在 model 中的 `packages.js` 有 `description` 字段的描述信息 `description: DataTypes.STRING`  不过我不知道如何修改这个 string 类型的长度

**Comment by L-Jovi** [comment]
感谢  我在 codepush.sql 中看到了描述信息的 sql 语句

再次感谢你的耐心

致意

**Comment by lisong** [comment]
orm 中的 `DataTypes.STRING` 没有长度，错误信息是mysql服务器抛出来的，当时我设置的description可能有点小。
