### ISSUE TITLE
IOS: The update contents failed the data integrity check

### ISSUE THREAD

**Issue by yqz0203** [lisong/code-push-server#174]
ios第一次发布版本，可以正常更新下来，然后后面如果正常更新，就会报

`The update contents failed the data integrity check`。

尝试过清理 `.DS_Store` 等文件，没有效果。

bundle目录结构为
```
- /assets
- main.js
- main.js.meta
- manifest.json // 这个文件是自己项目用的
```

如果尝试删除 `manifest.json` 文件，则下一次就能成功更新。但是如果再下一次的热更没有这个文件，仍然会更新失败。

安卓手机测试过并没此问题。

**Comment by yqz0203** [comment]
@lisong 请问下这是什么原因呢。

**Comment by yqz0203** [comment]
找到原因了，如果通过删除 `.DS_Store` 文件无法解决时，可以参考下这个。。。真的是神坑。

此问题在之前官方server没有出现过，可能官方做了特殊处理。

_____________

经过2天的折腾和调试，发现IOS更新后的packagehash值始终和接口返回的不一致。

然后将bundle进行了本地计算，从而排除了服务端计算错误的可能性。那么问题只有可能出现在 `code-push` native包的算法上。

将客户端生成的 `manifestData` 以及序列化后的字符串和server的做了完整对比，看起来是一样的。但是长度上差了2个字符（开始没在意，殊不知这是问题的根源）。

OC源码有替换路径的逻辑：

``` objective-c
// The JSON serialization turns path separators into "\/", e.g. "CodePush\/assets\/image.png"
    manifestString = [manifestString stringByReplacingOccurrencesOfString:@"\\/"
                                                               withString:@"/"];
```

将替换后的值在编辑器中查看后，发现有一个文件路径中有一个 '\/' 没有被替换。用vscode全局匹配，又能正常替换，于是把目光放到了这个 `stringByReplacingOccurrencesOfString` 方法上，心想是不是方法有问题，本人不怎么会OC，找同事帮忙+google，就是找不到这个方法的毛病。。

最后，想起了网上曾经有一个小哥因为同事的一个特殊字符差点崩溃的故事，心想该不会也是这个问题吧。。

结果在那个路径上尝试删除，果然前面字符没有被删除，说明有一个看不见的字符在这里！


![image](https://user-images.githubusercontent.com/8850879/51383922-bc7d2900-1b55-11e9-8dab-a2ba941cfed3.png)

问题就出现在文件名第一个字符 `q` 前面有一个看不见的字符，将路径分隔符 `/` 转换成了一个其他字符。

如果大家无论怎么试都难以更新成功，甚至成功率随缘，可以尝试下看看自己的文件名有无此类问题。


但是安卓端为什么没这个问题呢？可能是这个符号在安卓被忽略了？后续再研究。。

**Comment by Kay0806** [comment]
文件名什么问题  我怎么没看明白

**Comment by zhllucky** [comment]
你好。我这边现在也有这个问题。但是怎么找到是哪个文件呢。

**Comment by gaoneng102** [comment]
https://github.com/lisong/code-push-server/issues/100#issuecomment-570780043
