### ISSUE TITLE
code-push-server  是否能够解决高并发

### ISSUE THREAD

**Issue by xiongcaichang** [lisong/code-push-server#18]
如果我们的app需求：同时数十万的客户端在哪请求更新，请问code-push-server  的数据库机制能够解决吗？谢啦

**Comment by lisong** [comment]
没有做过压力测试，用nginx做负载均衡，支持水平扩展，压力确实在数据库端。如果配上数据库5.7并发10万应该没有问题。只有updateCheck需要为此做下优化，加缓存。考虑到只有打开app的时候才请求更新，所以就没有做此优化

**Comment by lisong** [comment]
也可以考虑在前面加varnish缓存可能效果会更好。

**Comment by lisong** [comment]
http://itbilu.com/nodejs/npm/VydcPndib.html
现在可以通过配置读写分离解决并发问题。多加slave机器

**Comment by lisong** [comment]
v2.0.10 中 updateCheck Api 添加了redis cache。这样高并发不成问题了
