### ISSUE TITLE
iOS update 304

### ISSUE THREAD

**Issue by iOSQiao** [lisong/code-push-server#194]
code-push-server, iOS移动端第一次更新成功，第二次更新，有下载进度提示，但是下载完成后并没有使用最新的bundle包。排查了一下，只有在第二次请求updateCheck的时候，返回了304状态码。安卓就不会出现这个问题。

**Comment by wMellon** [comment]
你好，请问这是什么问题，我也遇到了

**Comment by iOSQiao** [comment]
校验的问题
