### ISSUE TITLE
七牛云存储的配置，对bucket类型有要求吗，公共或者私有？

### ISSUE THREAD

**Issue by gordonpro** [lisong/code-push-server#2]
本地存储的我测试过了，可以用了

**Comment by lisong** [comment]
创建空间时，可设置为公开空间或私有空间。

公开空间，可通过文件对象的 URL 直接访问。如果要使用七牛云存储的镜像存储功能，请设置空间的属性为公有。

私有空间，文件对象的访问则必须获得拥有者的授权才能访问。

公开和私有仅对空间的读文件生效，修改、删除、写入等对空间的操作均需要拥有者的授权才能进行操作。

**Comment by lisong** [comment]
设置为私有空间，意味着每次下载都需要请求一次授权，react-native-code-push不支持，也没有意义。
