### ISSUE TITLE
app检查更新一直访问 https://codepush.azurewebsites.net 而不是自己服务器的地址

### ISSUE THREAD

**Issue by shouhuori** [lisong/code-push-server#204]
在Xcode配置了CodePushServerUrl为自己的url，请问还需要在react native 项目里配置么。

**Comment by shouhuori** [comment]
把CodePushServerUrl 改成CodePushServerURL就解决了

**Comment by iaminvictus1993** [comment]
> 把CodePushServerUrl 改成CodePushServerURL就解决了

请问在哪改啊?我安卓也一直请求codepush.azurewebsites.net

**Comment by upcwangying** [comment]
@iaminvictus1993 https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md
https://github.com/microsoft/react-native-code-push/blob/master/docs/multi-deployment-testing-ios.md
https://www.jianshu.com/p/417a165ca9d7
