### ISSUE TITLE
我在 Linux 系统上安装报如下错误。

### ISSUE THREAD

**Issue by nobodyhi** [lisong/code-push-server#21]
`npm ERR! Linux 2.6.32-504.el6.x86_64
npm ERR! argv "/weblogic/code-push/node-v6.6.0-linux-x64/bin/node" "/weblogic/code-push/node-v6.6.0-linux-x64/bin/npm" "install"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /weblogic/code-push/code-push-server/npm-debug.log

`

**Comment by lisong** [comment]
npm 最低版本为 v3.10.8 你的是v3.10.3, 升级npm
```shell
$ npm install npm@next -g
```
