### ISSUE TITLE
App更新一直报网络出错[CodePush] Network request failed，使用code-push deployment h huDemo Production --format json，报错[Error]  Cannot read property 'label' of null

### ISSUE THREAD

**Issue by xiaomei991** [lisong/code-push-server#215]
![image](https://user-images.githubusercontent.com/20355401/62919720-1edd9580-bdd6-11e9-8b91-4eea5f0ea1b4.png)

![image](https://user-images.githubusercontent.com/20355401/62919768-40d71800-bdd6-11e9-822a-2c07fa907ebf.png)

![image](https://user-images.githubusercontent.com/20355401/62919840-72e87a00-bdd6-11e9-9506-d5ea366e96d6.png)

请问这个是什么问题呢

**Comment by lisong** [comment]
已经修复
