### ISSUE TITLE
这个问题 我是在接入  react native 0.60 版本 不能检测更新

### ISSUE THREAD

**Issue by zkkg2018** [lisong/code-push-server#219]
<img width="1126" alt="WX20190822-154817@2x" src="https://user-images.githubusercontent.com/41882148/63496338-4f1ee580-c4f4-11e9-95ea-9de789dc9236.png">
大佬们有没有解决的方案

**Comment by lisong** [comment]
同 https://github.com/lisong/code-push-server/issues/220

**Comment by lingmingchang** [comment]
请问，这个问题你解决了么？
我把版本回退到5.6.0，但是大于5.6.0版本的APP收不到更新

**Comment by gao520sun** [comment]
请问这个问题什么时候解决呢？
