### ISSUE TITLE
react-native-code-push 5.7.0无法更新，code-push的检测地址变了，望修复

### ISSUE THREAD

**Issue by zim-lee** [lisong/code-push-server#220]
现在的检测地址变成了：`/v0.1/public/codepush/update_check?deployment_key=xxx&app_version=xxx&client_unique_id=xxx`
附带的参数名称也变了

**Comment by lisong** [comment]
👌

**Comment by maxrisk** [comment]
我也是无法更新

**Comment by pig3800** [comment]
请问暂时有什么临时解决方案吗？谢谢

**Comment by zim-lee** [comment]
> 请问暂时有什么临时解决方案吗？谢谢

等待修复期间，只能把`react-native-code-push`回退到5.6.x版本

**Comment by sunny635533** [comment]
I  use react-native-code-push in 5.6.0,  this error didnt appear again!

**Comment by mark5566** [comment]
> I use react-native-code-push in 5.6.0, this error didnt appear again!

same error in 5.6.1

**Comment by mark5566** [comment]
http://xx.xx.xx.xx:3000/updateCheck?deploymentKey=kkkkkk&appVersion=1.0.0&client_unique_id=FD0871F2-D606-4C4A-B306-18C714D152E5

**Comment by mark5566** [comment]
http://xx.xx.xx.xx:3000/updateCheck?deploymentKey=kkkkkk&appVersion=1.0.0&client_unique_id=FD0871F2-D606-4C4A-B306-18C714D152E5
react-native-code-push@5.5.1

**Comment by sunny635533** [comment]
@mark5566 maybe you can try delete package.lock ,and delete node_modules, then run "npm install". But dont forget to set react-native-code-push@5.6.0!

**Comment by mark5566** [comment]
@sunny635533 Okay ，thanks

**Comment by a26364177** [comment]
作者修好了
只是沒push到npm上可以pull github的最新commit

**Comment by a26364177** [comment]
npm install https://github.com/lisong/code-push-server.git

**Comment by lingmingchang** [comment]
请问，这个问题你解决了么？
我把版本回退到5.6.0，但是大于5.6.0版本的APP收不到更新。

**Comment by a26364177** [comment]
Sgithub上最新的三個commit 更新上你的server

lingmc <notifications@github.com>於 2019年9月16日 週一，下午5:35寫道：

**Comment by nolan12345** [comment]
use "react-native-code-push": "git+https://git@github.com/lisong/react-native-code-push.git" instead "react-native-code-push": "x.x.x" in package.json
This approach solved my problem, other solutions didn't work

**Comment by nolan12345** [comment]
use "react-native-code-push": "git+https://git@github.com/lisong/react-native-code-push.git" instead "react-native-code-push": "x.x.x" in package.json
This approach solved my problem, other solutions didn't work

**Comment by nolan12345** [comment]
use "react-native-code-push": "git+https://git@github.com/lisong/react-native-code-push.git" instead "react-native-code-push": "x.x.x" in package.json
This approach solved my problem, other solutions didn't work

**Comment by rixinop** [comment]
[CodePush] 400: An update check must include a binary version that conforms to the semver standard (e.g. '1.0.0'). The binary version is normally inferred from the App Store/Play Store version configured with your app  报了这个问题

**Comment by rixinop** [comment]
[CodePush] 400: An update check must include a binary version that conforms to the semver standard (e.g. '1.0.0'). The binary version is normally inferred from the App Store/Play Store version configured with your app   ----------------------code-push 报了这个问题 ， 说我的版本号不符合标准，我改了有可能的版本号，都不行， 在哪里可以改他这个版本号

**Comment by zim-lee** [comment]
@rixinop 版本号建议3位，x.x.x这样的，另外这个issue已经解决了，大家有问题新开issue吧，这个作者已经解决了，先关闭了

**Comment by xclidongbo** [comment]
这个解决了吗? 我试过只有使用5.6.0版本才能热更新, 以上版本都是404

**Comment by marlti7** [comment]
还是这问题啊 解决了吗

**Comment by marlti7** [comment]
5.6.0 对于CodePush(没有参数), 找不到合适的构造器

`/Users/mq-zy/Documents/roshi/roshi/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:112: 错误: 对于CodePush(没有参数), 找不到合适的构造器
      new CodePush(),
      ^
    构造器 CodePush.CodePush(String,Context)不适用
      (实际参数列表和形式参数列表长度不同)
    构造器 CodePush.CodePush(String,Context,boolean)不适用
      (实际参数列表和形式参数列表长度不同)
    构造器 CodePush.CodePush(String,Context,boolean,String)不适用
      (实际参数列表和形式参数列表长度不同)
    构造器 CodePush.CodePush(String,Context,boolean,int)不适用
      (实际参数列表和形式参数列表长度不同)
    构造器 CodePush.CodePush(String,Context,boolean,String,Integer)不适用
      (实际参数列表和形式参数列表长度不同)`

**Comment by marlti7** [comment]
@lisong @xclidongbo

**Comment by xclidongbo** [comment]
> 5.6.0 对于CodePush(没有参数), 找不到合适的构造器
> 
> `/Users/mq-zy/Documents/roshi/roshi/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:112: 错误: 对于CodePush(没有参数), 找不到合适的构造器 new CodePush(), ^ 构造器 CodePush.CodePush(String,Context)不适用 (实际参数列表和形式参数列表长度不同) 构造器 CodePush.CodePush(String,Context,boolean)不适用 (实际参数列表和形式参数列表长度不同) 构造器 CodePush.CodePush(String,Context,boolean,String)不适用 (实际参数列表和形式参数列表长度不同) 构造器 CodePush.CodePush(String,Context,boolean,int)不适用 (实际参数列表和形式参数列表长度不同) 构造器 CodePush.CodePush(String,Context,boolean,String,Integer)不适用 (实际参数列表和形式参数列表长度不同)`

我今天也遇到这个问题了。
