### ISSUE TITLE
pm2 下运行默认账号不能登录

### ISSUE THREAD

**Issue by weberliu** [lisong/code-push-server#23]
/bin/www 运行可以用默认账号登录，用 pm2 启动登录时提示 secret must be a string or buffer

**Comment by lisong** [comment]
指定配置文件没？

**Comment by weberliu** [comment]
指定的是同一个config文件

**Comment by lisong** [comment]
你的代码应该是master里面的，master里面的config.js有更新，需要配置 `jwt`.`sercetToken`

**Comment by lisong** [comment]
`/bin/www 运行可以用默认账号登录，用 pm2 启动登录时提示 secret must be a string or buffer`
pm2 中的 CONFIG_FILE应该没有生效

**Comment by weberliu** [comment]
奇怪的是我输入123456登录有这个提示，但我随便输入点什么的时候就提示密码不对了

**Comment by lisong** [comment]
你pm2是用什么启动的？ 是docs/process.yml 配置的么？

**Comment by weberliu** [comment]
是的。不过我修改完密码后就可以登录了。

ps: 修改密码的文档有错，最后我是通过 postman 修改成功的。
