### ISSUE TITLE
总是提示 app up to date

### ISSUE THREAD

**Issue by dawnvan** [lisong/code-push-server#25]
![image](https://cloud.githubusercontent.com/assets/1756449/20835135/db0d3e46-b8d3-11e6-802d-0f09a7941dca.png)

**Comment by dawnvan** [comment]
不管是用你的服务器还是用我自己搭建的

**Comment by lisong** [comment]
整个app的图片给我看看

**Comment by dawnvan** [comment]
![image](https://cloud.githubusercontent.com/assets/1756449/20836721/892c2ce2-b8db-11e6-9c4a-fd84d5b61667.png)

**Comment by dawnvan** [comment]
我QQ：2588234 ，能否加您，我研究了1整天都是这样
