### ISSUE TITLE
我这边每次都是下载的完整的包1.6m，实际上只更改了一行代码，请问这是什么原因呢

### ISSUE THREAD

**Issue by 17554265585** [lisong/code-push-server#253]
是因为我没有做这一步吗
use "react-native-code-push": "git+https://git@github.com/lisong/react-native-code-push.git" instead "react-native-code-push": "x.x.x" in package.json
因为我做了这一步会报找不到'DiffMatchPatch.h' file not found

**Comment by 17554265585** [comment]
"description": "",
    "isDisabled": false,
    "isMandatory": false,
    "rollout": 100,
    "appVersion": "1.0.3",
    "packageHash": "0b57d419e663740baeacd1e7ca6e09affd3c05c164ad7651e2ab7d4a2afb1991",
    "blobUrl": "https://www.chaxiaoyin.cn/download/fu/Fu6KQXIGYSBItSARYntMLKFEiDHs",
    "size": 1630822,
    "manifestBlobUrl": "https://www.chaxiaoyin.cn/download/fk/FkgjZtDP8SsADr4nPZxvX-hVWRU2",
    "diffPackageMap": null,
    "releaseMethod": "Upload",
    "uploadTime": 1574223331000,
    "originalLabel": "",
    "originalDeployment": "",
    "label": "v13",
    "releasedBy": "lisong2010@gmail.com",
    "metrics": {
      "active": 0,
      "downloaded": 1,
      "failed": 0,
      "installed": 0,
      "totalActive": 10
    }

diffPackageMap这个始终是null

**Comment by THROFHR** [comment]
最后是怎么解决的？还有，同样是 'DiffMatchPatch.h' file not found 问题

**Comment by xclidongbo** [comment]
@THROFHR  咋样, 能解决吗?

**Comment by THROFHR** [comment]
@xclidongbo 目前没有

**Comment by xclidongbo** [comment]
@THROFHR 
我刚才试出来了. CodePush 5.6.0版本是可用的, 5.6.0以上版本就是404错误.
