### ISSUE TITLE
请问如果使用你提供的react-native-code-push的话，如何链接呢

### ISSUE THREAD

**Issue by 17554265585** [lisong/code-push-server#254]
如果使用pod，会报'DiffMatchPatch.h' file not found
如果按react-native-code-push官网的手动链接方法会有很多头文件找不到，因为很多头文件是用的#import <JWTCoding.h> 而不是#import "JWTCoding.h"，修改成#import "JWTCoding.h"后会报599 duplicate symbols for architecture x86_64

**Comment by huang-ju** [comment]
同样遇到这个问题，怎样才能解决？ @17554265585

**Comment by huang-ju** [comment]
我回滚版本解决了，没有用google diff-match-patch

**Comment by xclidongbo** [comment]
@huang-ju  怎么解决的?

**Comment by bardliu** [comment]
> @huang-ju 怎么解决的?
修改以下内容，然后重新 run `pod install`.
### CodePush.podspec
```
- s.source_files   = 'ios/CodePush/*.{h,m}'
+ s.source_files   = ['ios/CodePush/*.{h,m}', 'ios/CodePush/DiffMatchPatch']

+s.requires_arc  = 'ios/CodePush/*.{h,m}'
```
### CodePushPackage.m
```
- #import "DiffMatchPatch.h"
+ #import "DiffMatchPatch/DiffMatchPatch.h"
```
