### ISSUE TITLE
关于 Docker 部署完成后，出现An unknown error occurred的问题

### ISSUE THREAD

**Issue by QAZDER** [lisong/code-push-server#270]
针对 **执行完release-react 之后，storage/data对应的目录下已经生成下载文件后台仍然报404错误** 这种情况

跟了代码之后，发现是下载路径的问题参考 #221 (应该是rn版本>0.57导致的)
此时需要修改package.json中react-native-code-push的安装路径
```
 "react-native-code-push": "git+https://git@github.com/lisong/react-native-code-push.git",
```
work out~
仅供参考

**Comment by xclidongbo** [comment]
@QAZDER  兄弟, 你这安装路径我没看懂... 有DEMO没.
