### ISSUE TITLE
不支持windows [运行code-push-server出错]

### ISSUE THREAD

**Issue by jacobcyl** [lisong/code-push-server#28]
Please create dir /Users/tablee/workspaces/storage
> C:\Users\Administrator\AppData\Roaming\npm\node_modules\code-push-server\app.js:57
    throw new Error(`Please create dir ${dir}`);

在windows下创建上述目录失败，因为这是linux系统下的路径格式，能否支持一下window路径？

**Comment by lisong** [comment]
可以配置window dir的

**Comment by lisong** [comment]
这个文件夹是自己指定的，不一定需要叫这个名字

**Comment by 17554265585** [comment]
是在config.js指定吗？为什么写了我自己的路径还是报这个错，仿佛没生效
