### ISSUE TITLE
code-push-server-db 命令出错

### ISSUE THREAD

**Issue by lin493369** [lisong/code-push-server#29]
@lisong 帮忙看一下创建服务器时候出的这个错误
![image](https://cloud.githubusercontent.com/assets/8255169/21518749/7ba559d4-cd23-11e6-9fd5-04151e458b54.png)

**Comment by ccgitgit** [comment]
你mysql有密码，在 --dbpassword 加上你的密码即可。但是后面启动web服务时候还会有类似问题，我也不知道code-push-server 这步如何能带密码参数运行，后来没办法我是直接改config/config.js里db配置    password: process.env.RDS_PASSWORD || “YourPassword”，有更好的解决方法请告知，谢谢了。

**Comment by lisong** [comment]
线上使用pm2管理应用，参考[pm2](https://github.com/lisong/code-push-server/blob/master/README.md#production-manage)
指定自己的config配置，参考[config](https://github.com/lisong/code-push-server/blob/master/README.md#run)
