### ISSUE TITLE
关于更新包的Hash

### ISSUE THREAD

**Issue by gordonpro** [lisong/code-push-server#3]
CodePush 有个 package_hash 。
这个值是在客户端 code-push release 的时候在客户端产生然后发送给服务器保存的 ，
还是更新包zip文件发送到服务器端了之后，服务器端hash得到的值？

**Comment by gordonpro** [comment]
我目前只找到有个 etag 产生的代码在服务器端。 这个和qiniu有关的把

**Comment by lisong** [comment]
package hash是根据每个文件的hash算出来的，相当于文件夹签名，所以只要文件内容不变hash值不会变，react-native-code-push更新时都会check下载好的包hash值是否一致，一致才会更新成功

**Comment by lisong** [comment]
永远不要相信客户端传过来的数据，这些都是服务器端计算的，算法是sha256
