### ISSUE TITLE
code-push 发布 release 包后，应用获取更新包错误

### ISSUE THREAD

**Issue by lin493369** [lisong/code-push-server#30]
使用 code-push release-react <AppName>-ios ios -d Production 打包并发布后
启动待更新应用，应用没有更新。
本地服务器Shell 报以下错误，烦请指示一下哪里配置不对了 @lisong 

![image](https://cloud.githubusercontent.com/assets/8255169/21536306/25114a9e-cdbc-11e6-8818-285b2a95d113.png)

![image](https://cloud.githubusercontent.com/assets/8255169/21536310/2fb7aa38-cdbc-11e6-9719-05e13f14d0ed.png)

**Comment by lisong** [comment]
应该是客户端 YourCodePushServerUrl 配置有问题  GET /%20/updateCheck  多空格了

**Comment by lin493369** [comment]
@lisong 谢谢，的确是 YourCodePushServerUrl 多了个空格。
再请教一个问题，我看到您这边搭的服务器后台有个 我的秘钥 和 应用列表，这部分是开源的吗？如果是开源的，怎么样运行这部分程序，谢谢！

**Comment by lisong** [comment]
https://github.com/lisong/code-push-web

**Comment by lin493369** [comment]
Thx.
