### ISSUE TITLE
code-push login 404

### ISSUE THREAD

**Issue by 465965092** [lisong/code-push-server#303]
使用命令code-push login http://127.0.0.1:3000后，浏览器打开的页面是http://127.0.0.1:3000/cli-login?hostname=User-2020KPQSUS，页面错误404

**Comment by 465965092** [comment]
经测试 安装code-push-cli-r 登陆成功，希望有大神继续维护项目

**Comment by liarman** [comment]
> 使用命令code-push login [http://127.0.0.1:3000后，浏览器打开的页面是http://127.0.0.1:3000/cli-login?hostname=User-2020KPQSUS，页面错误404](http://127.0.0.1:3000%E5%90%8E%EF%BC%8C%E6%B5%8F%E8%A7%88%E5%99%A8%E6%89%93%E5%BC%80%E7%9A%84%E9%A1%B5%E9%9D%A2%E6%98%AFhttp://127.0.0.1:3000/cli-login?hostname=User-2020KPQSUS%EF%BC%8C%E9%A1%B5%E9%9D%A2%E9%94%99%E8%AF%AF404)
不要用最新版的code push，用旧版本的才可以用。
