### ISSUE TITLE
Login Token 怎么设置不失效

### ISSUE THREAD

**Issue by zkluna** [lisong/code-push-server#304]
code-push login 登录授权之后，过段时间(几天或者几周)登录授权会失效，怎么让授权不失效？

**Comment by cmcreborn** [comment]
> code-push login 登录授权之后，过段时间(几天或者几周)登录授权会失效，怎么让授权不失效？

auth.js
`jwt.sign({ uid: users.id, hash: security.md5(users.ack_code), expiredIn: 7200 }, tokenSecret)`
修改 expiredIn參數

**Comment by zkluna** [comment]
感谢回答。已经写好处理脚本，在使用前判断登录状态，失效的就重新授权一次。
