### ISSUE TITLE
[Android] code-push issue with --mandatory option

### ISSUE THREAD

**Issue by devhyunjae** [lisong/code-push-server#31]
1. code-push cli command

```
code-push release-react MYAPP android -m true -d Production
```

2. after complete if i look at my release history

![screen shot 2016-12-29 at 5 25 34 pm](https://cloud.githubusercontent.com/assets/12890257/21539663/458b7c2e-cdec-11e6-84b6-b8e4dcfff960.png)

mandatory option shows no. both v6, v7 was released with mandatory option

3. If i open the app to get the new code-pushed bundle, the app crashes

4. And then, when i reopen the app, now the app works with the new pushed bundle.

Any clues to guess? 😰

**Comment by lisong** [comment]
I'm so sorry, I were misunderstood  mandatory meaning. I were thought it must update binary app。
so i  mandatory follows app version。i will fix it，thanks
