### ISSUE TITLE
targetBinaryVersion 参数问题

### ISSUE THREAD

**Issue by zhangqqqf** [lisong/code-push-server#33]
code-push release-cordova  使用 -t 参数,即--targetBinaryVersion 参数
一直报错不支持的版本号, 是该功能未实现么?

**Comment by lisong** [comment]
只支持精确匹配版本

**Comment by anhuiliujun** [comment]
有没有考虑支持--targetBinaryVersion "~1.1.0"这种版本的计划

**Comment by lisong** [comment]
做这个版本匹配很简单就能做到，主要担心用户如果没有管理好，app版本和package之间的依赖关系，匹配更新会导致严重后果

**Comment by treemore** [comment]
请问一下能不能这么写
-t "2.0.1"
-t "2.0.2"
-t "2.0.3"
-t "2.0.4"
