### ISSUE TITLE
code-push-server-db init --dbhost localhost --dbuser root --dbpassword  报错

### ISSUE THREAD

**Issue by juanq123** [lisong/code-push-server#36]
当我执行
code-push-server-db init --dbhost localhost --dbuser root --dbpassword 
的时候报错
{ [Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)]
  cause: 
   { [Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)]
     code: 'ER_ACCESS_DENIED_ERROR',
     errno: 1045,
     sqlState: '28000',
     fatal: true },
  isOperational: true,
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlState: '2800

**Comment by juanq123** [comment]
是不是需要自己搭建数据库啊，提前

**Comment by lisong** [comment]
是的
