### ISSUE TITLE
提示文件格式不对

### ISSUE THREAD

**Issue by juanq123** [lisong/code-push-server#39]
bogon:code-push-demo-app-master jq$ code-push release  CodePushDemo-android  ./bundles/index.android.bundle 1.0.0 --deploymentName Production  --description "1.支持文章缓存。" --mandatory true
Upload progress:[==================================================] 100% 0.0s
[Error]  上传的文件格式不对

**Comment by lisong** [comment]
不支持单个文件发布，使用目录发布形式，将bundle放到一个目录中，发布整个目录
