### ISSUE TITLE
Login一进去就是404

### ISSUE THREAD

**Issue by void117** [lisong/code-push-server#4]
请问是还有什么没说明清楚的要做的步骤吗？因为是这方面的新手可能有些地方不是很明白，谢谢了。

**Comment by lisong** [comment]
你的配置文件是啥样子的?

**Comment by lisong** [comment]
把config/config.js 中codePushWebUrl配置去掉，这个配置是跳转到https://github.com/lisong/code-push-web服务上

**Comment by void117** [comment]
可以了，谢谢
