### ISSUE TITLE
How to modify the password

### ISSUE THREAD

**Issue by yccphp** [lisong/code-push-server#43]
After the installation is complete, open the address login, the default account password is admin, 123456

How do I change it

**Comment by yccphp** [comment]
Thank you, carefully read the document, have found the answer

```
$ curl -X PATCH -H "Authorization: Bearer mytoken" -H "Accept: application/json" -H "Content-Type:application/json" -d '{"oldPassword":"123456","newPassword":"654321"}' http://127.0.0.1:3000/users/password
```

**Comment by lisong** [comment]
直接表里面加吧，如果通过注册的方式，还需要配置邮件和redis

**Comment by ypchris** [comment]
> 直接表里面加吧，如果通过注册的方式，还需要配置邮件和redis

你好，这个用户的密码使用的是什么加密方式？
