### ISSUE TITLE
建议使用generator的形式

### ISSUE THREAD

**Issue by ElvisKang** [lisong/code-push-server#44]
通过CLI的generate指令在指定目录下创建一个服务器实例，这样便于配置、管理（尤其是需要运行多个server实例时）和定制，同时也比clone github的代码更加友好。

**Comment by lisong** [comment]
可以使用 `npm install code-push-server -g` 安装

**Comment by ElvisKang** [comment]
npm install code-push-server -g 的形式个人认为等价于clone github 代码一次

如果我想为两个app分别配置不同的服务器进程的话该如何操作？

**Comment by lisong** [comment]
有类似的例子推荐么？需要参考一下

**Comment by ElvisKang** [comment]
个人的设想就是前端项目借助[yo](https://github.com/yeoman/yo)创建一个脚手架，然后开发者在这上面进行扩展、配置
