### ISSUE TITLE
code-push release-react 部署包导致code-push-server进程退出

### ISSUE THREAD

**Issue by anhuiliujun** [lisong/code-push-server#45]
使用如下命令部署
```
code-push release-react finance-android android --description "13. 测试提示" -d "Production" -m
```

服务端错误日志：

```
0|code-pus | { Error: ENOENT: no such file or directory, chmod '/home/ubuntu/storage/FkrEhz92120pOEqjFY5zUhi9Teoz'
0|code-pus |   errno: -2,
0|code-pus |   code: 'ENOENT',
0|code-pus |   syscall: 'chmod',
0|code-pus |   path: '/home/ubuntu/storage/FkrEhz92120pOEqjFY5zUhi9Teoz' }
0|code-pus | Error: ENOENT: no such file or directory, open '/tmp/codepush_DZ6SFf4vUBZwgKvTzMLOpzn2ZElmjH2Y/FgJjaMWow7_70N7g29IezDkkwl19.zip'
PM2        | App [code-push-server] with id [0] and pid [21423], exited with code [1] via signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:code-push-server id:0
PM2        | App name:code-push-server id:0 online
```

可以看出code-push-server进程是退出了，但是由于使用了pm2管理并开启watch，所以又重启了。

不知道为什么会出现这样的错误，还请指教

**Comment by anhuiliujun** [comment]
另外，我有个疑问：使用local的方式，历史版本是如何维护的，永远不删除吗？

**Comment by lisong** [comment]
需要创建文件夹`/home/ubuntu/storage`, local方式和其他云存储并无区别，只是分发的package存储在机器端，非云端

**Comment by yccphp** [comment]
@lisong  我用的七牛，也会报以下错误

```
Executing (default): SELECT `id`, `package_id`, `diff_against_package_hash`, `diff_blob_url`, `diff_size`, `created_at`, `updated_at` FROM `packages_diff` AS `PackagesDiff` WHERE `PackagesDiff`.`package_id` = 11 AND `PackagesDiff`.`diff_against_package_hash` = '78603d11fd5ef995e4fcd818214af977612dd2c6b357fb91d6f59dadb8aa6965' LIMIT 1;
{ message: 'request fail' }
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/tmp/codepush_QGMTuZ6LyFeS9prj1w8U1krMCjRlv2ES/FvN5NclpgKjfdV3Ef0VnQU8cxVwD_hotcodepush'
    at Error (native)

```

**Comment by anhuiliujun** [comment]
@lisong 我这个文件夹是存在的，奇怪的是，虽然进程退出了，但是好像部署是成功的，
```
![image](https://cloud.githubusercontent.com/assets/721395/22098447/553c72a6-de61-11e6-9686-67524e473eae.png)
```

**Comment by lisong** [comment]
master上已经修复

**Comment by anhuiliujun** [comment]
还是会出现进程退出的情况

**Comment by lisong** [comment]
能提供一下具体日志么？

**Comment by anhuiliujun** [comment]
```
{ Error: ENOENT: no such file or directory, chmod '/usr/share/nginx/html/download/Fk4H65Ipx3081NdasuhY-yQaRgf8'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'chmod',
  path: '/usr/share/nginx/html/download/Fk4H65Ipx3081NdasuhY-yQaRgf8' }
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/tmp/codepush_KO5EFN6gy60jC3mwr3pfy2XT4zbd3zmN/Fl6vpbaiL0G3K15RmfBAOuBYq2Xh.zip'
    at Error (native)
```

**Comment by anhuiliujun** [comment]
和之前的错误是一样的

**Comment by lisong** [comment]
已更新，这种情况，可能是没有权限读写/tmp/目录

**Comment by heronlyj** [comment]
@lisong 你好，我用 master 最新的代码，也出现了同样的问题，请问有什么解决方案吗

```
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at common.createFileFromRequest.then (/root/codePush/server/core/services/package-manager.js:199:35)
    at tryCatcher (/root/codePush/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/codePush/server/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/root/codePush/server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/root/codePush/server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/root/codePush/server/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/root/codePush/server/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/root/codePush/server/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/root/codePush/server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/tmp/codepush_JXWSzpnP33pwIqTXa4cQUNr614OKLeTo/Fp17KQw9TqqEHS-rTRUQknpPV7SX_hotcodepush'
    at Error (native)
```

**Comment by jiabinxu** [comment]
Error: ENOENT: no such file or directory, open '/tmp/codepush_DZ6SFf4vUBZwgKv
我看过tmp文件夹权限是rwt但缓存文件中并没有codepush文件夹，对这个问题不太了解，希望能告知解决方案，谢谢🙏

**Comment by cnpmge** [comment]
请问具体是怎么解决的？我每次提交新的版本，服务器停止一次，需要重新启动
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, stat 'C:\Users\ADMINI~1\AppData\Local\
Temp\2\codepush_pEtKyhOpatlF5wuymi40UxPa3McOqK3L\c9357f00e60827ebdb8ef028ddd01a9
62f470cecf062fc21375eb1dc6dc57d7b\dataCenter\CodePush\index.android.bundle'
Emitted 'error' event on ZipFile instance at:
    at C:\Users\Administrator\code-push-server\node_modules\[4myazl[24m\index.
js:30:26
[90m    at FSReqCallback.oncomplete (fs.js:158:21)[39m {
  errno: [33m-4058[39m,
  code: [32m'ENOENT'[39m,
  syscall: [32m'stat'[39m,
  path: [32m'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\codepush_pEtKyhOpatl
F5wuymi40UxPa3McOqK3L\\c9357f00e60827ebdb8ef028ddd01a962f470cecf062fc21375eb1dc6
dc57d7b\\dataCenter\\CodePush\\index.android.bundle'[39m
}

**Comment by Jetjiang911** [comment]
> 请问具体是怎么解决的？我每次提交新的版本，服务器停止一次，需要重新启动
> events.js:187
> throw er; // Unhandled 'error' event
> ^
> 
> Error: ENOENT: no such file or directory, stat 'C:\Users\ADMINI~1\AppData\Local Temp\2\codepush_pEtKyhOpatlF5wuymi40UxPa3McOqK3L\c9357f00e60827ebdb8ef028ddd01a9 62f470cecf062fc21375eb1dc6dc57d7b\dataCenter\CodePush\index.android.bundle' Emitted 'error' event on ZipFile instance at: at C:\Users\Administrator\code-push-server\node_modules\�[4myazl�[24m\index. js:30:26 �[90m at FSReqCallback.oncomplete (fs.js:158:21)�[39m { errno: �[33m-4058�[39m, code: �[32m'ENOENT'�[39m, syscall: �[32m'stat'�[39m, path: �[32m'C:\Users\ADMINI~1\AppData\Local\Temp\2\codepush_pEtKyhOpatl
> F5wuymi40UxPa3McOqK3L\c9357f00e60827ebdb8ef028ddd01a962f470cecf062fc21375eb1dc6
> dc57d7b\dataCenter\CodePush\index.android.bundle'�[39m
> }

你好，我这边也遇到了相同的问题，请问你那边解决了吗？

**Comment by cnpmge** [comment]
> > 请问具体是怎么解决的？我每次提交新的版本，服务器停止一次，需要重新启动
> > events.js:187
> > throw er; // Unhandled 'error' event
> > ^
> > Error: ENOENT: no such file or directory, stat 'C:\Users\ADMINI~1\AppData\Local Temp\2\codepush_pEtKyhOpatlF5wuymi40UxPa3McOqK3L\c9357f00e60827ebdb8ef028ddd01a9 62f470cecf062fc21375eb1dc6dc57d7b\dataCenter\CodePush\index.android.bundle' Emitted 'error' event on ZipFile instance at: at C:\Users\Administrator\code-push-server\node_modules\�[4myazl�[24m\index. js:30:26 �[90m at FSReqCallback.oncomplete (fs.js:158:21)�[39m { errno: �[33m-4058�[39m, code: �[32m'ENOENT'�[39m, syscall: �[32m'stat'�[39m, path: �[32m'C:\Users\ADMINI~1\AppData\Local\Temp\2\codepush_pEtKyhOpatl
> > F5wuymi40UxPa3McOqK3L\c9357f00e60827ebdb8ef028ddd01a962f470cecf062fc21375eb1dc6
> > dc57d7b\dataCenter\CodePush\index.android.bundle'�[39m
> > }
> 
> 你好，我这边也遇到了相同的问题，请问你那边解决了吗？

跳过x.x.0这个版本号，从x.x.1开始，我不知道解决没解决反正跳过这个x.x.0服务器就不会重启
