### ISSUE TITLE
[Error]  EACCES: permission denied, mkdir '/Users'

### ISSUE THREAD

**Issue by yuyixg** [lisong/code-push-server#46]
客户端发布报如下错误
[Error]  EACCES: permission denied, mkdir '/Users'

**Comment by yuyixg** [comment]
搞定了，服务端权限问题，用root启动nodejs即可

**Comment by lisong** [comment]
配置文件中的目录修改成自己的，然新建相应的目录

**Comment by Qggld** [comment]
怎样解决的啊  求解   我服务端按照它的要求新建了users目录 最后告诉我socket hang up

**Comment by lisong** [comment]
该配置文件呀
