### ISSUE TITLE
请问下如何修改账户信息

### ISSUE THREAD

**Issue by L-Jovi** [lisong/code-push-server#47]
看到默认使用的账户是 `lisong2010@gmail.com`

使用 code-push register http://[myhost] 后发现到了登录界面  输入数据库里初始的用户名密码后发现后台报错

![image](https://cloud.githubusercontent.com/assets/7262199/22578855/b5bfa1ba-ea06-11e6-977a-101ed801ea3f.png)

。。想默默问下怎么注册新的邮箱账户

感谢 :)

**Comment by lisong** [comment]
注册接口有提供，需要配合界面 https://github.com/lisong/code-push-web

**Comment by L-Jovi** [comment]
感谢回复
