### ISSUE TITLE
有时候莫名的更新错误，服务死掉了

### ISSUE THREAD

**Issue by juanq123** [lisong/code-push-server#48]
有时候莫名的更新错误，服务死掉了，请问遇到过，遇到过没有啊

**Comment by lisong** [comment]
更新到最新版本么？

**Comment by lisong** [comment]
最好用pm2管理进程，能提供日志么？

**Comment by juanq123** [comment]
[Error]  connect ECONNREFUSED 113.31.136.151:3000
JQdeMacBook-Pro:code-push-demo-app-master jq$ code-push logout
[Error]  connect ECONNREFUSED 113.31.136.151:3000
JQdeMacBook-Pro:code-push-demo-app-master jq$ code-push login http://xx.xx.xx.xx:3000 
[Error]  You are already logged in from this machine.

**Comment by lisong** [comment]
113.31.136.151:3000 服务是开的么？
无法登陆出去，可以直接删除 ~/.code-push.config文件

**Comment by lisong** [comment]
线上使用pm2管理应用，参考[pm2](https://github.com/lisong/code-push-server/blob/master/README.md#production-manage)
指定自己的config配置，参考[config](https://github.com/lisong/code-push-server/blob/master/README.md#run)

**Comment by lisong** [comment]
已经修复，如果还出现类似问题，可以开启debug log模式记录日志反馈
