### ISSUE TITLE
更新的时候出现unknown error

### ISSUE THREAD

**Issue by void117** [lisong/code-push-server#5]
点击更新按钮之后，出现下载弹窗，然后点击安装后就会显示unknown error。查看了服务端发现有查询packages_diff表，但我看了一下那个表里是空的。请教一下可能是什么原因导致这个错误呢？

**Comment by lisong** [comment]
packages_diff表是差异化表，如果是只发了一个版本，就没有数据，没有数据没有关系，你的是iOS还是Android上?

**Comment by lisong** [comment]
如果服务和手机不在同一台机器上就需要修改 config/config.js 文件中downloadUrl的配置localhost改成你机器的IP地址或者域名

**Comment by void117** [comment]
谢谢！确实是这个问题
