### ISSUE TITLE
客户端获取更新报错-An unknown error occurred

### ISSUE THREAD

**Issue by ccgitgit** [lisong/code-push-server#51]
我远程服务器上搭的push-code-server，配置的qiniu，发布更新qiniu bucket能收到文件，server的库表里也ok，但是客户端访问时报错An unknown error occurred（我复制的demo.js做rn客户端内容），每当客户端启动server都会报一次以下错误。
![1](https://cloud.githubusercontent.com/assets/15956861/22685454/5864e586-ed5b-11e6-9080-23d6fc090519.png)

**Comment by lisong** [comment]
检查downloadUrl是否配置正确
```
code-push deployment h CodePushDemo-ios Production —format=json
```
输出信息是？

**Comment by ccgitgit** [comment]
code-push deployment h CodePushDemo-android Production --format=json
[
  {
    "description": "",
    "isDisabled": false,
    "isMandatory": false,
    "rollout": 100,
    "appVersion": "1.0.0",
    "packageHash": "c0466e74591faf3e9221e07ef4b7087e320784dcd3ac45db33f76d979096593e",
    "blobUrl": "http://7xqojf.com1.z0.glb.clouddn.com/Fp1OkvBkuZORLeyMpBcnaR29jT9U",
    "size": 199301,
    "manifestBlobUrl": "http://7xqojf.com1.z0.glb.clouddn.com/FqCbIKzFiegGGaASMj37AmSLpQa6",
    "diffPackageMap": {
      "b023012a85c76599c13aa9e1ebe855ee5ad3b243bb263e797833df0dbef6beb5": {
        "size": 167786,
        "url": "http://7xqojf.com1.z0.glb.clouddn.com/Fh6qJuxtbYHwQ1IT0LKfxX5qJhB_"
      }
    },
    "releaseMethod": "Upload",
    "uploadTime": 1486459452000,
    "originalLabel": "",
    "originalDeployment": "",
    "label": "v3",
    "releasedBy": "lisong2010@gmail.com"
  },
  {
    "description": "",
    "isDisabled": false,
    "isMandatory": false,
    "rollout": 100,
    "appVersion": "1.0.0",
    "packageHash": "b023012a85c76599c13aa9e1ebe855ee5ad3b243bb263e797833df0dbef6beb5",
    "blobUrl": "http://7xqojf.com1.z0.glb.clouddn.com/FmfWsLpKYHXX8LeM3mBpdr6EmGkM",
    "size": 199302,
    "manifestBlobUrl": "http://7xqojf.com1.z0.glb.clouddn.com/FjoQsDxMSkrVSX4LAxS30N7mP0Li",
    "diffPackageMap": null,
    "releaseMethod": "Upload",
    "uploadTime": 1486457079000,
    "originalLabel": "",
    "originalDeployment": "",
    "label": "v2",
    "releasedBy": "lisong2010@gmail.com"
  },
  {
    "description": "",
    "isDisabled": false,
    "isMandatory": false,
    "rollout": 100,
    "appVersion": "1.0.0",
    "packageHash": "72be57e1ba35260e8d470de5c84ee7b4eb40bbbaa74aa83daa7fa70108bbc595",
    "blobUrl": "http://7xqojf.com1.z0.glb.clouddn.com/FtWQs1c3F3Ve5S70WlxFGrXic1xN",
    "size": 199301,
    "manifestBlobUrl": "http://7xqojf.com1.z0.glb.clouddn.com/FjG_pYBKQes3pRumdXHMAwlWZXoZ",
    "diffPackageMap": null,
    "releaseMethod": "Upload",
    "uploadTime": 1486456764000,
    "originalLabel": "",
    "originalDeployment": "",
    "label": "v1",
    "releasedBy": "lisong2010@gmail.com"
  }
]

**Comment by lisong** [comment]
客户端url配置多了个空格

**Comment by ccgitgit** [comment]
确实，多谢了

**Comment by andylidong** [comment]
qiniu: {
    accessKey: "",
    secretKey: "",
    bucketName: "",
    downloadUrl: "" // Binary files download host address.
  },
前面两个我知道怎么弄，会面呢？
    bucketName: "download",
    downloadUrl: "http://http://7xqojf.com1.z0.glb.clouddn.com/download" 
这样可以吗

**Comment by tututututututu** [comment]
[
  {
    "description": "",
    "isDisabled": false,
    "isMandatory": false,
    "rollout": 100,
    "appVersion": "1.0.1",
    "packageHash": "11f3ec4d2e32d2a89e5d4ea5489a9f8ba1d51e0641c2671b1b9db5c0ceac4474",
    "blobUrl": "http://192.168.1.19:3000/download/fv/FvayAUKXLK1AkS5BrwUbsP7YrphW",
    "size": 217321,
    "manifestBlobUrl": "http://192.168.1.19:3000/download/fu/Fu9IwaEfwU4iG_XqSfUgteTDTdTb",
    "diffPackageMap": null,
    "releaseMethod": "Upload",
    "uploadTime": 1561465590000,
    "originalLabel": "",
    "originalDeployment": "",
    "label": "v1",
    "releasedBy": "lisong2010@gmail.com",
    "metrics": {
      "active": 0,
      "downloaded": 0,
      "failed": 0,
      "installed": 0,
      "totalActive": 0
    }
  }
]


我的提示[CodePush] Network request failed  请帮我看看是什么问题 谢谢.
以下是我的 docker-compose.yml文件内容
`version: "3.7"
services:
  server:
    image: tablee/code-push-server:v0.5.2
    volumes:
      - data-storage:/data/storage
      - data-tmp:/data/tmp
      - ./config.js:/config.js
    environment:
      DOWNLOAD_URL: "http://192.168.1.19:3000/download"
      MYSQL_HOST: "192.168.1.19"
      MYSQL_PORT: "3308"
      MYSQL_USERNAME: "codepush"
      MYSQL_PASSWORD: "123456"
      MYSQL_DATABASE: "codepush"
      STORAGE_DIR: "/data/storage"
      DATA_DIR: "/data/tmp"
      NODE_ENV: "production"
      CONFIG_FILE: "/config.js"
      REDIS_HOST: "192.168.1.19"
      REDIS_PORT: "6388"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1000M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    networks:
      - servernet
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7.23
    volumes:
      - data-mysql:/var/lib/mysql
      - ./sql/codepush-all.sql:/docker-entrypoint-initdb.d/codepush-all.sql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "On"
    networks:
      - dbnet
  redis:
    image: redis:4.0.11-alpine
    volumes:
      - data-redis:/data
    ports:
      - "6388:6379"
    networks:
      - redisnet
networks:
  servernet:
  dbnet:
  redisnet:
volumes:
  data-storage:
  data-tmp:
  data-mysql:
  data-redis:
`
