### ISSUE TITLE
如果我命令行code-push-cli 已经登陆一个服务器，但是那个服务器已经销毁了

### ISSUE THREAD

**Issue by juanq123** [lisong/code-push-server#53]
如果我命令行code-push-cli 已经登陆一个服务器，但是那个服务器已经销毁了，code-push logout 登出超时，怎么解决，我想登陆一个新的服务器

**Comment by lisong** [comment]
用户目录中的隐藏文件`.code-push.config` 记录登录信息的，直接删除，相当于退出
