### ISSUE TITLE
你好  请问下我们的这个服务器如何加一层 https 服务

### ISSUE THREAD

**Issue by L-Jovi** [lisong/code-push-server#58]
如题  因为我们这个服务器是直接使用 node 自己的 server  我想加一层 auth 之后再暴露到外面  想问下有木有办法

感谢

**Comment by lisong** [comment]
使用nginx做loadbalance

**Comment by L-Jovi** [comment]
感谢回复  如果我想用 node 自己实现可以嘛   不借助 nginx 的前提下

**Comment by lisong** [comment]
不建议在应用server端做这个，毕竟如果你的业务增长，需要加server实例的，加一层loadbalance并非画蛇添足。而且nginx配置多个code-push-server实例，可以保证高可用性

**Comment by L-Jovi** [comment]
感谢  明白了
