### ISSUE TITLE
无法上传index.android.bundle

### ISSUE THREAD

**Issue by WangJintong** [lisong/code-push-server#6]
我使用 code-push release ... ./bundle/index.android.bundle ....  会提示上传格式不对。
我使用 code-push release ... ./bundle ....  会提示 it must be publish it by ios type  。

请教一下，应该如何使用 code-push release 。 

谢谢。

**Comment by lisong** [comment]
推荐使用code-push release-react 该命令自动帮你打包

**Comment by lisong** [comment]
没有必要使用code-push release，参数多，而且容易出错。react-native不同平台bundle的包不一样，所以一个命令发布更好，防止iOS的包发到andriod上

**Comment by WangJintong** [comment]
我使用 code-push release-react myapp android  ，同样的错误出现：
it must be publish it by ios type .

**Comment by lisong** [comment]
之前 myapp有发布过没？

**Comment by lisong** [comment]
是不是作为ios项目发布过

**Comment by lisong** [comment]
项目名字必须要以 ios_ 或者android_ 为前缀，然后项目第一次发布后平台类型确认定了是不能更改的，否则android和ios平台版本会混乱

**Comment by WangJintong** [comment]
这样是不是不太合理？本身react native创建的应用，是在项目内部区分平台的，单独创建应用，岂不是意味着rn自创建的应用内，某个平台的代码是多余的？

**Comment by lisong** [comment]
发布的时候要区分，这个不冲突，react-native bundle的时候也是区分平台的，android大包规则和ios不一样，这是平台差异化

**Comment by WangJintong** [comment]
我临时将 pubType 强制为 android ，server 逻辑是否可正常工作？这种状态下我可以publish bundle文件，手机端可以发起同步请求，但是并没能完成update动作。
GET /updateCheck?deploymentKey=.....&appVersion=1.0.0&packageHash=&isCompanion=&label=&clientUniqueId=.... 200 136.051ms -340

**Comment by lisong** [comment]
说明没有检查到更新，你可以新建一个应用，这个限制其实还是蛮有用的，避免用户将andriod类型的bundle误更新到iOS机器上，可以浏览器直接请求/updateCheck?deploymentKey=.....&appVersion=1.0.0&packageHash=&isCompanion=&label=&clientUniqueId= 地址，返回结果是?

**Comment by lisong** [comment]
你这信息没有办法定位是服务器端问题还是客户端问题，要不你用这个 https://github.com/lisong/code-push-demo-app 例子，连接你搭好的服务器，确认好服务器端是ok后，再找找啥问题，客户端集成应该没有啥区别。react-native-code-push 客户端更新也有几种配置，我也踩过雷。例如：“我把更新检测代码写到异步进程里面，以为好些。但是每次更新都自动回顾回去。”

**Comment by WangJintong** [comment]
浏览器直接请求 updateCheck 的返回结果是：
{"updateInfo":{"downloadURL":"http://localhost:3000/download/FnrDpJniIUUPw1KeBWSE1LCtFjyR","description":"","isAvailable":true,"isMandatory":false,"appVersion":"1.0.0","packageHash":"3ed5069c5f8e5ef002464c7ef963653c222a4af4fc08b56ba24b33ffb088d713","label":"v1","packageSize":163416,"updateAppVersion":false,"shouldRunBinaryVersion":false}}

**Comment by WangJintong** [comment]
我试着编译了你的 code-push-demo-app 例子 ，还没能编译成功，不过我比对了你的demo和我的demo代码，只在一个地方存在差异：
new CodePush 时，我的第二个参数用了MainApplication.this,你的是getApplicationContext()。

**Comment by lisong** [comment]
按照返回结果是有更新包下载的，只是下载地址配置有问题，如果你用的android模拟器，你需要执行 ```adb reverse tcp:3000 tcp:3000``` 代理一下。参照 https://github.com/lisong/code-push-server/issues/5 配置一下

**Comment by WangJintong** [comment]
修改 config/config.js 文件中downloadUrl的配置localhost改成你机器的IP地址或者域名之后，OK。

**Comment by lisong** [comment]
## 正确使用code-push热更新

- 苹果允许使用热更新[Apple's developer agreement](https://developer.apple.com/programs/ios/information/iOS_Program_Information_4_3_15.pdf), 但是规定不能弹框提示用户更新，影响用户体验。 而Google Play恰好相反，必须弹框告知用户更新。然而中国的android市场都必须关闭更新弹框，否则会在审核应用时以“请上传最新版本的二进制应用包”驳回应用。
- react-native 不同平台bundle包不一样，在使用code-push-server的时候必须创建不同的应用来区分(eg. ios_CodePushDemo 和 android_CodePushDemo)
- react-native-code-push只更新资源文件,不会更新java和Objective C，所以npm升级依赖包版本的时候，如果依赖包使用的本地化实现, 这时候必须更改应用版本号(ios修改Info.plist中的CFBundleShortVersionString, android修改build.gradle中的versionName), 然后重新编译app发布到应用商店。
- 推荐使用code-push release-react 命令发布应用，该命令合并了打包和发布命令(eg. code-push release-react ios_CodePushDemo ios -d Production)

**Comment by acmelacross** [comment]
var os = require('os');

var config = {};
config.development = {
  // Config for database, only support mysql.
  db: {
    username: process.env.RDS_USERNAME || "root",
    password: process.env.RDS_PASSWORD || '1111',
    database: process.env.DATA_BASE || "codepush",
    host: process.env.RDS_HOST || "127.0.0.1",
    port: process.env.RDS_PORT || 3306,
    dialect: "mysql",
    logging: false,
    operatorsAliases: false,
  },
  // Config for qiniu (http://www.qiniu.com/) cloud storage when storageType value is "qiniu".
  qiniu: {
    accessKey: "",
    secretKey: "",
    bucketName: "",
    downloadUrl: "" // Binary files download host address.
  },
  // Config for upyun (https://www.upyun.com/) storage when storageType value is "upyun"
  upyun: {
    storageDir: process.env.UPYUN_STORAGE_DIR,
    serviceName: process.env.UPYUN_SERVICE_NAME,
    operatorName: process.env.UPYUN_OPERATOR_NAME,
    operatorPass: process.env.UPYUN_OPERATOR_PASS,
    downloadUrl: process.env.DOWNLOAD_URL,
  },
  // Config for Amazon s3 (https://aws.amazon.com/cn/s3/) storage when storageType value is "s3".
  s3: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
    sessionToken: process.env.AWS_SESSION_TOKEN, //(optional)
    bucketName: process.env.BUCKET_NAME,
    region: process.env.REGION,
    downloadUrl: process.env.DOWNLOAD_URL, // binary files download host address.
  },
  // Config for Aliyun OSS (https://www.aliyun.com/product/oss) when storageType value is "oss".
  oss: {
    accessKeyId: "",
    secretAccessKey: "",
    endpoint: "",
    bucketName: "",
    prefix: "", // Key prefix in object key
    downloadUrl: "", // binary files download host address.
  },
  // Config for tencentyun COS (https://cloud.tencent.com/product/cos) when storageType value is "oss".
  tencentcloud: {
    accessKeyId: "",
    secretAccessKey: "",
    bucketName: "",
    region: "",
    downloadUrl: "", // binary files download host address.
  },
  // Config for local storage when storageType value is "local".
  local: {
    // Binary files storage dir, Do not use tmpdir and it's public download dir.
    storageDir: process.env.STORAGE_DIR || "/Users/dev02/Desktop/working/demo/pushServer/storage",
    // Binary files download host address which Code Push Server listen to. the files storage in storageDir.
    downloadUrl: process.env.LOCAL_DOWNLOAD_URL || "http://127.0.0.1:3000/download",
    // public static download spacename.
    public: '/download'
  },
  jwt: {
    // Recommended: 63 random alpha-numeric characters
    // Generate using: https://www.grc.com/passwords.htm
   // tokenSecret: process.env.TOKEN_SECRET ||'INSERT_RANDOM_TOKEN_KEY'  MieNU6ugOdvfa8fG56kCL9F8VkCTy05vNVvMjrEiMLhEqkZzh9vIFtO2JlRxkKH
   tokenSecret:'MieNU6ugOdvfa8fG56kCL9F8VkCTy05vNVvMjrEiMLhEqkZzh9vIFtO2JlRxkKH'
  },
  common: {
    /*
     * tryLoginTimes is control login error times to avoid force attack.
     * if value is 0, no limit for login auth, it may not safe for account. when it's a number, it means you can
     * try that times today. but it need config redis server.
     */
    tryLoginTimes: 0,
    // CodePush Web(https://github.com/lisong/code-push-web) login address.
    //codePushWebUrl: "http://127.0.0.1:3001/login",
    // create patch updates's number. default value is 3
    diffNums: 3,
    // data dir for caclulate diff files. it's optimization.
    dataDir: process.env.DATA_DIR || os.tmpdir(),
    // storageType which is your binary package files store. options value is ("local" | "qiniu" | "s3"| "oss" || "tencentcloud")
    storageType: process.env.STORAGE_TYPE || "local",
    // options value is (true | false), when it's true, it will cache updateCheck results in redis.
    updateCheckCache: false,
    // options value is (true | false), when it's true, it will cache rollout results in redis
    rolloutClientUniqueIdCache: false,
  },
  // Config for smtp email，register module need validate user email project source https://github.com/nodemailer/nodemailer
  smtpConfig:{
    host: "smtp.aliyun.com",
    port: 465,
    secure: true,
    auth: {
      user: "",
      pass: ""
    }
  },
  // Config for redis (register module, tryLoginTimes module)
  redis: {
    default: {
      host: "127.0.0.1",
      port: 6379,
      retry_strategy: function (options) {
        if (options.error.code === 'ECONNREFUSED') {
          // End reconnecting on a specific error and flush all commands with a individual error
          return new Error('The server refused the connection');
        }
        if (options.total_retry_time > 1000 * 60 * 60) {
            // End reconnecting after a specific timeout and flush all commands with a individual error
            return new Error('Retry time exhausted');
        }
        if (options.times_connected > 10) {
            // End reconnecting with built in error
            return undefined;
        }
        // reconnect after
        return Math.max(options.attempt * 100, 3000);
      }
    }
  }
}

config.development.log4js = {
  appenders: {console: { type: 'console'}},
  categories : {
    "default": { appenders: ['console'], level:'error'},
    "startup": { appenders: ['console'], level:'info'},
    "http": { appenders: ['console'], level:'info'}
  }
}

config.production = Object.assign({}, config.development);
module.exports = config;

**Comment by acmelacross** [comment]
我也遇到了同样的问题   it must be publish it by ios type

**Comment by acmelacross** [comment]
我也遇到了同样的问题 it must be publish it by ios type   
可是我的downloadUrl: process.env.LOCAL_DOWNLOAD_URL || "http://127.0.0.1:3000/download",  已经改了啊
