### ISSUE TITLE
能够增加支持腾讯云和CDN不

### ISSUE THREAD

**Issue by sunneyoy** [lisong/code-push-server#60]
能够增加支持腾讯云和CDN不

**Comment by lisong** [comment]
cdn可以采用回源的方式，只需修改downloadurl，可以增加腾讯云适配

**Comment by sunneyoy** [comment]
cool

**Comment by lisong** [comment]
qcloud sdk 是不是还没有nodejs版本的？

**Comment by sunneyoy** [comment]
qcloud sdk 有nodejs的版本，qcloudapi-sdk

**Comment by sunneyoy** [comment]
https://github.com/CFETeam/qcloudapi-sdk

**Comment by lisong** [comment]
版本0.4.7已经支持该功能
