### ISSUE TITLE
如何进行增量更新？

### ISSUE THREAD

**Issue by jsntghf** [lisong/code-push-server#61]
支持增量更新的步骤是什么？需要做怎样的操作？

**Comment by lisong** [comment]
增量更新最小粒度是文件，对于文本diff-patch更新方式，react-native-code-push目前还不支持

**Comment by jsntghf** [comment]
对于文件的增量更新，如何生效？还是说默认就是用的增量更新？

**Comment by lisong** [comment]
默认就是增量更新，配置文件中的`diffNum`表示计算增量的往前追溯的版本数

**Comment by LittleLiByte** [comment]
感觉增量更新没有体现出来，我发布了两个不同的包，但是有挺多图片重复的
