### ISSUE TITLE
线上修改数据存如何做数据迁移和备份？

### ISSUE THREAD

**Issue by hwangjr** [lisong/code-push-server#64]
**描述**

原先我们直接采用本地存储（单机），但是由于我们的业务扩展，现在想将文件存储移动到 阿里云的OSS 上面。

**问题**

1. 数据库直接导出并进行迁移即可
2. 本地的存储文件需要如何进行迁移？   还是可以丢弃？

是否有一个比较完善的迁移的说明？

感谢开源此项目！

**Comment by lisong** [comment]
文件都上传到oss即可，然后配置成oss存储方式

**Comment by hwangjr** [comment]
ok。感谢。
