### ISSUE TITLE
阿里云OSS存储如果做CDN的话是否会导致更新失败

### ISSUE THREAD

**Issue by hwangjr** [lisong/code-push-server#65]
如果阿里云OSS做了CDN，上传文件到OSS之后，需要一定时间CDN才会生效，这样是否会导致用户更新到的文件还是旧的？针对这个是否有一些解决方法？还是目前不支持OSS的CDN？

**Comment by lisong** [comment]
每个版本hash值不一样，所以不会更新到旧的，cdn找不到最新的文件应该都会回源找，和你使用的那个企业的云存储都没有太大的关联

**Comment by hwangjr** [comment]
好的。感谢解答。
