### ISSUE TITLE
目前是否支持Cordova?

### ISSUE THREAD

**Issue by zsxsoft** [lisong/code-push-server#7]
貌似没搜到相关代码的样子

如果不支持，请问是否有支持计划？

**Comment by lisong** [comment]
回头我研究下，应该区别不大

**Comment by lisong** [comment]
支持cordova

```xml
<platform name="android">
    <preference name="CodePushDeploymentKey" value="BhQCC2gVHJqz6e1GkFO9fyx3HgPa4ksvOXqog" />
    <preference name="CodePushServerUrl" value="http://127.0.0.1:3000/" />
</platform>
<platform name="ios">
     <preference name="CodePushDeploymentKey" value="BhQCC2gVHJqz6e1GkFO9fyx3HgPa4ksvOXqog" />
     <preference name="CodePushServerUrl" value="http://127.0.0.1:3000/" />
</platform>
```

**Comment by Cui-y** [comment]
> 支持cordova
> 
> ```
> <platform name="android">
>     <preference name="CodePushDeploymentKey" value="BhQCC2gVHJqz6e1GkFO9fyx3HgPa4ksvOXqog" />
>     <preference name="CodePushServerUrl" value="http://127.0.0.1:3000/" />
> </platform>
> <platform name="ios">
>      <preference name="CodePushDeploymentKey" value="BhQCC2gVHJqz6e1GkFO9fyx3HgPa4ksvOXqog" />
>      <preference name="CodePushServerUrl" value="http://127.0.0.1:3000/" />
> </platform>
> ```

请问能将cordova 详细使用教程加进去么，这边没太明白应该怎么去使用热更新去搞定cordova app

**Comment by lisong** [comment]
参考微软官方例子，只需要在官方例子上再配置下自己的域名就可以
