### ISSUE TITLE
用户数据显示严重错误的现象

### ISSUE THREAD

**Issue by dalancon** [lisong/code-push-server#74]
![1f44003f-522e-4a45-95fb-850cadfc9d55](https://user-images.githubusercontent.com/4489404/28059715-ae0493ae-6657-11e7-8e17-68b9b0cea2c1.png)
![68681ebd-6259-4ebe-a09e-d88f6c727879](https://user-images.githubusercontent.com/4489404/28059716-af3c81e6-6657-11e7-996d-03eaadf23080.png)

1、用户更新成功和失败，调用逻辑一样，用户数只增不减
2、用户更新失败后，安装数应该不变，但现在仍然加1
3、逻辑里只见到packages metrics表数据+1的情况，未见到-1的情况
4、新版本升级成功后，以前老的版本对应的数据应该相应-1，目前未见到数据-1的情况

**Comment by lisong** [comment]
统计的哪里，微软接口返回设计得不太合理，所以也没有投入太多关注

**Comment by lisong** [comment]
同 https://github.com/lisong/code-push-server/issues/72
