### ISSUE TITLE
ios跨域请求失败问题

### ISSUE THREAD

**Issue by chaosx110** [lisong/code-push-server#76]
![image](https://user-images.githubusercontent.com/6712443/28166606-2044fe04-680b-11e7-83b0-c4c382375f93.png)
[预检请求正常返回]
![image](https://user-images.githubusercontent.com/6712443/28166039-f956d710-6808-11e7-845d-e10818a35bd1.png)
[后台接受到的数据请求]
部署code-push-server的时候，出现了一个让人很头疼的问题，在ios端进行更新时出现跨域预检请求成功，但是不会进行接下来的GET请求。其中xhr.readyStatus为4而xhr.status为0，没有得到有效的更新数据。求各位大神解答。。（另在android机上更新正常）

**Comment by lisong** [comment]
不会有跨域问题的呀

**Comment by kele1990** [comment]
i have the problem too

**Comment by BaiPeiHe** [comment]
I have the problem too，Is this problem solved?

**Comment by BaiPeiHe** [comment]
解决了这个问题，修改了 app.js里的响应头
app.all('*', function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept, Authorization, X-CodePush-Plugin-Version, X-CodePush-Plugin-Name, X-CodePush-SDK-Version");
  res.header("Access-Control-Allow-Methods","PUT,POST,GET,PATCH,DELETE,OPTIONS");
  log.debug("use set Access-Control Header");
  next();
  });

**Comment by kele1990** [comment]
@BaiPeiHe 我的cordova项目使用了wkwebview就会跨域，参考了你的的方法，解决了，多谢
