### ISSUE TITLE
能支持下--targetBinaryVersion "3.0.0-3.1.0" 这种多个版本一起发布的特性么？

### ISSUE THREAD

**Issue by gulullu** [lisong/code-push-server#77]
微软官方的是支持的，用自己搭建的会提示：“[Error]  targetBinaryVersion 3.0.0-3.1.0 not support.”，能不能支持下，每个版本都要发一次好累。

**Comment by zim-lee** [comment]
+1 多个版本一起发布功能很常用

**Comment by helloworldsmart** [comment]
+1 多个版本一起发布功能很常用

[Error]  targetBinaryVersion  not support. !!!!!!!!

**Comment by lisong** [comment]
多个版本发布可能会采坑，有些js bundle并不是支持匹配的二进制app版本，会出现兼容性问题，导致app运行隐藏。

**Comment by lisong** [comment]
v0.4.0支持该特性
