### ISSUE TITLE
How to change default host/port 0.0.0.0:3000 怎么修改默认端口

### ISSUE THREAD

**Issue by LinqVicky** [lisong/code-push-server#79]
文档中内容为
Default listen Host/Port 0.0.0.0/3000
you can change like this.
$ PORT=3000 HOST=127.0.0.1 NODE_ENV=production node ./bin/www # or PORT=3000 HOST=127.0.0.1 NODE_ENV=production code-push-server

在命令行中执行PORT=3000 HOST=127.0.0.1 NODE_ENV=production code-push-server
会提示 
'PORT' 不是内部或外部命令，也不是可运行的程序或批处理文件。
应该怎么修改？求详细说明

**Comment by lisong** [comment]
windows下面 将PORT HOST设置到环境变量里面

**Comment by LinqVicky** [comment]
@lisong 怎么设置啊？ PORT HOST 变量值是什么？能否辛苦详细点或者上个图么？ 非常感谢

**Comment by LinqVicky** [comment]
添加PORT环境变量设置端口号后，已修改端口。 谢谢
