### ISSUE TITLE
我更新包，出现unknow error错误，可以正确下载更新包，但执行更新时报错

### ISSUE THREAD

**Issue by cncowboy** [lisong/code-push-server#8]
帮忙分析一下，谢谢

**Comment by lisong** [comment]
参考 https://github.com/lisong/code-push-server/issues/5

**Comment by cncowboy** [comment]
谢谢回复，和#5的情况不一样，我的配置是正确的，可以正确下载更新包，但下载后更新才报错。
另外我把code push server改成微软件的就没有问题，一切正常。

**Comment by cncowboy** [comment]
不好意思，刚才出去了
http://119.29.137.66:3000/updateCheck?deploymentKey=StsBGoIc7UiI5k9VQBPCCRJsqYsw4ksvOXqog&appVersion=1.0.0&packageHash=965cac8b1d68f1f64f1cd991cc9df1bd03b5f120550f86fee161bde2d6f756ba&isCompanion=&label=&clientUniqueId=375784D6-DE06-42F2-8BB8-B708D32F7983

{"updateInfo":{"downloadURL":"http://119.29.137.66:3000/download/Fgz5oy5S6svevHmIUNeynp3SQMCO","description":"","isAvailable":true,"isMandatory":false,"appVersion":"1.0.0","packageHash":"684949f4493f9874b829c60c8e1c00e10c1fc72845fe292da7a544f393acd42c","label":"v7","packageSize":1340434,"updateAppVersion":false,"shouldRunBinaryVersion":false}}

**Comment by lisong** [comment]
下载的包好像有点问题，你能不能用code-push release-react 这个命令发布一下

**Comment by cncowboy** [comment]
可是我提交到微软code push server用的是相同的方法，
不过我试试你的意见。
麻烦帮我指出，你觉得有问题是哪几点？

**Comment by lisong** [comment]
把你的打包命令发在这里一下，因为我没有用过code-push release 发布过应用，可能目录结构有点问题，回头我看一下

**Comment by cncowboy** [comment]
我比较了一下，目录结构确实不一样
react native 打包：
node node_modules/react-native/local-cli/cli.js bundle --entry-file index.ios.js --bundle-output ios/bundles/main.jsbundle --platform 'ios' --assets-dest ./ios/bundles  --dev false --reset-cache
code-push 打包，上传：
code-push release rn_ride ./ios/bundles 1.0.0

**Comment by lisong** [comment]
目录结构倒是其次

**Comment by cncowboy** [comment]
我的qq是8080958,如果有必须你可以远程到我的机器上看一下

**Comment by lisong** [comment]
环境我可以模拟的，我还是建议你使用code-push release-react 打包， 简单而且不容易出错，这个bug在下一个版本我也会修复

**Comment by cncowboy** [comment]
好的，我再试试，谢谢

**Comment by lisong** [comment]
我刚才按照你的方式试验了一下，我这边可以发布。你的code-push-server和react-native版本是？

**Comment by cncowboy** [comment]
code-push-server是我从你git库中拉的最新代码，
"react-native": "0.31.0"
code-push-cli是最新的

**Comment by lisong** [comment]
用release-react命令是不是好的?

**Comment by lisong** [comment]
你这个问题解决没？

**Comment by zhangchenna** [comment]
能否发布一个详细的安装说明

**Comment by lisong** [comment]
涉及到的，readme里面都提到了呀

**Comment by zhangchenna** [comment]
Error: connect ECONNREFUSED 127.0.0.1:3306  这是因为没装 mysql-server吗

**Comment by lisong** [comment]
是的

**Comment by zhangchenna** [comment]
我也遇到楼上的问题，push更新版本，但是无法收到更新。求解，

**Comment by lisong** [comment]
https://github.com/lisong/code-push-server/issues/5 是这种问题么？麻烦把你的配置文件贴一下

**Comment by zhangchenna** [comment]
local: {
    // Binary files storage dir, Do not use tmpdir and it's public download dir.
    storageDir: "/home/wwwroot/code-push-server/storage",
    // Binary files download host address which Code Push Server listen to. the files storage in storageDir.
    downloadUrl: "127.0.0.1/download/",
    // public static download spacename.
    //public: '/download'
  },

就改了这个地方 比如jwt commn 这些需要改吗   目前是 unknow error

**Comment by lisong** [comment]
`downloadUrl: "http://127.0.0.1:3000/download/" `

**Comment by zhangchenna** [comment]
是有http的

**Comment by lisong** [comment]
https://127.0.0.1:3000/updateCheck?deploymentKey=YOUR_KEY&appVersion=1.0.0&packageHash=&isCompanion=false&label=&clientUniqueId=8A622DF0-D118-4B2D-915B-D9FF0F474EA8 将YOUR_KEY换成你的deploymentKey,返回的结果是？

**Comment by rollandlau** [comment]
@lisong @zhangchenna 
返回是这样的：
```json
{"updateInfo":{"downloadURL":"http://rndbg.hidizhu.com/download//FuzW3CuuGjO08HAzN3hTx3F13d_D","description":"","isAvailable":true,"isMandatory":false,"appVersion":"1.1","packageHash":"23c7d94b6f41f5b17043fbec33a2852e1cacb554c21e60ea4e236538500fbd08","label":"v1","packageSize":165006,"updateAppVersion":false,"shouldRunBinaryVersion":false}}
```

现在的问题是：可以正常下载更新文件，但是在应用时会提示无效。
上传更新的命令是：
```bash
code-push release-react localstrip-android android -d Production
```
而且上传是成功的

**Comment by lisong** [comment]
`http://rndbg.hidizhu.com/download//FuzW3CuuGjO08HAzN3hTx3F13d_D`
这个地址可以下载文件么？

**Comment by zhangchenna** [comment]
去掉了，访问后是Error: Not Found
Error: Not Found
   at /home/wwwroot/code-push-server/app.js:71:13
   at Layer.handle [as handle_request] (/home/wwwroot/code-push-server/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/home/wwwroot/code-push-server/node_modules/express/lib/router/index.js:312:13)
   at /home/wwwroot/code-push-server/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/home/wwwroot/code-push-server/node_modules/express/lib/router/index.js:330:12)
   at next (/home/wwwroot/code-push-server/node_modules/express/lib/router/index.js:271:10)
   at /home/wwwroot/code-push-server/node_modules/express/lib/router/index.js:618:15
   at next (/home/wwwroot/code-push-server/node_modules/express/lib/router/index.js:256:14)
   at Function.handle (/home/wwwroot/code-push-server/node_modules/express/lib/router/index.js:176:3)
   at router (/home/wwwroot/code-push-server/node_modules/express/lib/router/index.js:46:12)
   at Layer.handle [as handle_request] (/home/wwwroot/code-push-server/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/home/wwwroot/code-push-server/node_modules/express/lib/router/index.js:312:13)
   at /home/wwwroot/code-push-server/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/home/wwwroot/code-push-server/node_modules/express/lib/router/index.js:330:12)
   at next (/home/wwwroot/code-push-server/node_modules/express/lib/router/index.js:271:10)
   at next (/home/wwwroot/code-push-server/node_modules/express/lib/router/route.js:121:14)

**Comment by lisong** [comment]
看你的目录下面有没有这个文件。说明没有下载文件

**Comment by zhangchenna** [comment]
依旧是error

**Comment by zhangchenna** [comment]
没有这个，是什么问题呢，路径不对吗？download？？

**Comment by lisong** [comment]
是不是 /home/wwwroot/code-push-server/storage 目录没有写权限

**Comment by zhangchenna** [comment]
有storage的权限也都有，里面也有东西的

**Comment by zhangchenna** [comment]
权限都加了

**Comment by lisong** [comment]
config 中的 public 值是？

**Comment by lisong** [comment]
你的用的是那个版本？

**Comment by zhangchenna** [comment]
是最新版，就改了个local里面的和数据库连接，其他都没又给改，如果可以能发一分你得全套给我吗250655604@qq.com

**Comment by lisong** [comment]
这个已经是全部的呀

**Comment by zhangchenna** [comment]
你的sql有三个，用哪个是正确的

**Comment by lisong** [comment]
三个都要执行，有初始化脚本的，readme中有提到，然后配置可以看config.js中的注释解释

**Comment by zhangchenna** [comment]
好吧，只用了一个

**Comment by lisong** [comment]
为啥不阅读一下readme，里面有初始化命令的
`./bin/db init --dbhost localhost --dbuser root --dbpassword`

**Comment by zhangchenna** [comment]
config.test这个也要导入是么？

**Comment by zhangchenna** [comment]
还有你得demo app报错多了个@  还有13行报错不知道为啥，删了就好了

**Comment by lisong** [comment]
错误信息是？
用config.js就可以，每个字段都读一遍
```
  jwt: {
    // 登录jwt签名密钥，必须更改，否则有安全隐患，可以使用随机生成的字符串
    // Recommended: 63 random alpha-numeric characters
    // Generate using: https://www.grc.com/passwords.htm
    tokenSecret: 'INSERT_RANDOM_TOKEN_KEY'
  },
```
tokenSecret 值一定要改，改成什么， https://www.grc.com/passwords.htm 网页中的随机数

**Comment by lisong** [comment]
demo app 中的@是比较新的ES语法，所以必须要添加依赖包 `babel-preset-react-native-stage-0`，如果有这个依赖包不应该会报错的

**Comment by rollandlau** [comment]
目前看来原因是Android项目中，MainApplication.java没有重载getJSBundleFile这个方法，使得下载更新的bundle后，codepush没法使用正确的文件名读取文件。我印象中和codepush相关的方法重载代码是自动添加的，其他几个重载和微软官方例子是一致的，但是getJSBundleFile似乎被忽略了

**Comment by lisong** [comment]
问题解决没？

**Comment by rollandlau** [comment]
现在可以了，我觉得cncowboy虽然没说话，但是问题很可能和我这个是一样的，close吧

**Comment by lisong** [comment]
ok

**Comment by syuenkei** [comment]
我出现同样的问题 
react-native项目
 ::ffff:192.168.31.220 - - "GET /download
/fu/Fuhq9QTFyGahxTrrNavTKz1QZGKH HTTP/1.1" 404 2500 "" "undefined" 
config.js中配置：
  local: {
    // Binary files storage dir, Do not use tmpdir and it's public download dir.
    storageDir:  "e:\\server\\codepush",
    // Binary files download host address which Code Push Server listen to. the files storage in storageDir.
    downloadUrl: "http://192.168.31.220:3000/download",
    // public static download spacename.
    public: process.env.PUBLIC || '/download'
  },
code-push-server更新后相应文件夹下有内容
我执行
http://127.0.0.1:3000/updateCheck?deploymentKey=iDrG0TZ40QFqDiNy8IjL4UAFTCxu4ksvOXqog&appVersion=1.0.0&packageHash=&isCompanion=false&label=&clientUniqueId=8A622DF0-D118-4B2D-915B-D9FF0F474EA8返回的结果是
{
updateInfo: {
downloadURL: "",
downloadUrl: "",
description: "",
isAvailable: false,
isMandatory: false,
appVersion: "1.0.0",
packageHash: "",
label: "",
packageSize: 0,
updateAppVersion: false,
shouldRunBinaryVersion: false
}
}
请问这是什么问题 项目中的配置 new CodePush("9kUTMfXYoi0d8GdCEe6e4dk0ntWX4ksvOXqog", getApplicationContext(), BuildConfig.DEBUG, "http://192.168.31.220:3000/") @lisong @zhangchenna
