### ISSUE TITLE
npm install时报错

### ISSUE THREAD

**Issue by gaozhuo** [lisong/code-push-server#80]
E:\codepush\code-push-server-master>npm install

> typechecker@2.0.8 preinstall E:\codepush\code-push-server-master\node_modules\
.staging\typechecker-7b84d7b6
> node ./cyclic.js

> typechecker@2.0.8 preinstall E:\codepush\code-push-server-master\node_modules\
.staging\typechecker-ed010d9d
> node ./cyclic.js

> code-push-server@0.2.19 prepublish E:\codepush\code-push-server-master
> npm run snyk-protect

> code-push-server@0.2.19 snyk-protect E:\codepush\code-push-server-master
> snyk protect

Snyk couldn't patch the specified vulnerabilities because GNU's patch is not ava
ilable. Please install 'patch' and try again.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "snyk-protect"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! code-push-server@0.2.19 snyk-protect: `snyk protect`

**Comment by lisong** [comment]
重新fetch master，去掉了snyk模块

**Comment by localSummer** [comment]
推荐使用yarn
