### ISSUE TITLE
android app无法更新的问题

### ISSUE THREAD

**Issue by tcwdsg** [lisong/code-push-server#82]
你好，我是用code-push的新手，可能有低级错误但是的确没有解决，我描述一下问题：
1. 按照你的文档和code-push官方文档配置好了react-native项目（基本都是默认配置）
2. 给安卓客户端打包了1.0.1版app，安装到了手机
3. 发布了1.0.2的staging和production
4. 然后发现怎么启动app都不会更新到1.0.2

现象，每次app启动都回去发这个请求
http://我的.域名/updateCheck?deploymentKey=[我的production-key]&appVersion=1.0.1&packageHash=&isCompanion=&label=&clientUniqueId=21aa5a63b1a4ff04

然后返回内容是
{"updateInfo":{"downloadURL":"http://我的.域名/download/Fp_qzl9WyMIUEqguixAPkEjsFDFV","description":"","isAvailable":true,"isMandatory":false,"appVersion":"1.0.1","packageHash":"a0df1b6857ced6ebc933bf70bcfcf14caf0ea5f254948d897f194f19bdbd4d48","label":"v1","packageSize":651266,"updateAppVersion":false,"shouldRunBinaryVersion":false}}

看了数据库1.0.2是有的，为何updateInfo不返回1.0.2

**Comment by lisong** [comment]
appversion 是APP二进制包的版本号

**Comment by tcwdsg** [comment]
谢谢，问题解决了

**Comment by jacintoface** [comment]
请问怎么解决的呢，我现在也是这个问题
