### ISSUE TITLE
初始化mysql数据库出现连接错误

### ISSUE THREAD

**Issue by Kariko** [lisong/code-push-server#84]
![default](https://user-images.githubusercontent.com/14925329/29545576-b4a9bd34-8721-11e7-8cee-951cb0a4f00d.png)
请问这个问题怎么解决？

**Comment by lisong** [comment]
有安装MySQL-server没？

**Comment by Kariko** [comment]
@lisong 
您好，上面的错误确实是没有mysql引起的，但是安装完后又出现错误：**ER_ACCESS_DENIED_ERROR**

**Comment by Kariko** [comment]
已解决，需要在--dbpassword 后面加上数据库的密码
