### ISSUE TITLE
运行./bin/www出现错误NotFoundError: Not Found

### ISSUE THREAD

**Issue by Kariko** [lisong/code-push-server#87]
![f ux qt1bvqhk0adz 2hdro](https://user-images.githubusercontent.com/14925329/29605952-4cba5112-881f-11e7-954f-de1e1fa64f51.png)
如上，从运行./bin/www开始就报这个错，一开始还没造成什么影响，但是后面我进行更新的时候就一直出错更新不了，也是上面这个错误
把项目release-react到服务器上的时候出现错误：
![default](https://user-images.githubusercontent.com/14925329/29606144-ebf4ad72-881f-11e7-81fc-7f4356a0572a.png)

**Comment by Kariko** [comment]
运行时候报错应该是因为我的地址多个空格，修改之后上传到服务器也不出错了，但是在手机上更新依旧出现该错误，请问是什么原因呢？

**Comment by JacobSo** [comment]
如果配置为local，需要把所有local配置的或符号||以及前面的条件移除，只需要留下我们自己配置。我同样遇到这个问题是这样解决的。

**Comment by lighthx** [comment]
哈?用了楼上的解决办法依然还是这个错误
