### ISSUE TITLE
目前是否支持多账号使用

### ISSUE THREAD

**Issue by tza17313** [lisong/code-push-server#88]
目前有多个项目用到了热更新服务，但是都是放在admin账号下；
没法针对使用人员设置权限，存在安全隐患，不知是否支持多账号的使用和权限分配

**Comment by lisong** [comment]
支持多账号的

**Comment by tza17313** [comment]
@lisong  能麻烦提供下文档的地址吗？谢谢啦 😊

**Comment by tza17313** [comment]
多账号需要config.js 里配好redis，然后就使用 `code-push-web` 里的可视化界面注册账号；
如果没redis 也可以修改这两个地方，绕过redis的验证；

![image](https://user-images.githubusercontent.com/2976095/34811590-9245a96c-f6dc-11e7-93ac-9c85f8b980b3.png)
![image](https://user-images.githubusercontent.com/2976095/34811624-b57390e8-f6dc-11e7-9441-22f9ec6edf76.png)

`code-push-web` 地址： https://github.com/lisong/code-push-web
