### ISSUE TITLE
请教一个关于promote的问题。

### ISSUE THREAD

**Issue by treemore** [lisong/code-push-server#90]
毫无疑问这个库太牛了，在微软没开源后端的情况下能直接兼容code-push。
但是在实际使用中有个问题，是不是不支持 promote的--targetBinaryVersion 配置？

看了下代码 /core/services/package-manager.js 这个文件的proto.promotePackage方法应该就是处理promote的吧。 好像每次promote只会将最新版本的deployment_version 提升到发布包。  没有办法提升老的发布版本？
既然都支持release的多个原生版本了，为什么不支持promote 针对多个原生版本进行promote呢？ 
或者你们有什么考虑？

**Comment by lisong** [comment]
--targetBinaryVersion这个参数应该是后面加的，可以适配这一特性
