### ISSUE TITLE
正确使用code-push热更新中的第五条

### ISSUE THREAD

**Issue by sword-art** [lisong/code-push-server#91]
每次发版本，都要部署一次codepush，为什么第一次部署的codepush也会被下载

**Comment by lisong** [comment]
iOS应该不会这样，andriod确实有bug https://github.com/Microsoft/react-native-code-push/issues/1000

**Comment by openUmbrella** [comment]
在我的项目中, iOS项目也会出现这个问题。通过抓包如下：
![image](https://user-images.githubusercontent.com/17615716/57745578-528a2000-7700-11e9-8be5-bd33f998c351.png)
我认为是本地的原始包的hash值和服务器的更新包的hash值不一样，才会触发更新。

**Comment by lisong** [comment]
是的，andriod首次按照无法拿到资源文件，andriod将资源文件也压缩到apk包里面，需要通过反编译获取，所以andriod首次安装无法增量更新

**Comment by openUmbrella** [comment]
@lisong 你好,可是我的是iOS项目啊，我确保代码没有改动，同时打包的命令参数也是一致的。但是最终的hash值却不一样。我不知道问题出在哪里了。

**Comment by openUmbrella** [comment]
经过一番排查，上面提到的问题的原因是因为RN预先设置了在运行项目过程中，先会执行react-native-xcode.sh脚本，而这个脚本的主要目的是打RN包，然后保存到App包内，也就是执行 react-native bundle命令，其中的dev参数的值是根据iOS模式下决定的，debug模式下是true，其他的是false。而我在运行项目时，是在debug模式下使用真机来跑的，app里面的main.jsbundle其实是react-native-xcode.sh脚本新打的dev为true的main.jsbundle包（如果在运行app之前手动将打好的包引入，会被脚本新打的到替换掉）。而我们上传到服务器的main.jsbundle包dev为false。由于打包时的dev参数的值不同，导致了main.jsbundle包不同，再进而导致了两个main.jsbundle的hash值不同，最终计算的hash也就不同了。
其实如果是在生产环境的话，就不会出现这个问题了。
希望大家能够借鉴，别再掉坑里了
