### ISSUE TITLE
客户端获取更新报错-An unknown error occurred

### ISSUE THREAD

**Issue by andylidong** [lisong/code-push-server#94]
[
  {
    "description": "",
    "isDisabled": false,
    "isMandatory": false,
    "rollout": 100,
    "appVersion": "1.2",
    "packageHash": "86b11c573a2cebfc95315c40e5c5ed9a07d753650cd8809fe00795c10c426e62",
    "blobUrl": "http://owvyxjk6r.bkt.clouddn.com/Fi55YANGiw1NF9kElQirj-1DJ66E",
    "size": 1033466,
    "manifestBlobUrl": "http://owvyxjk6r.bkt.clouddn.com/FuEpc2vg6YqhA7vqHKxu3JCCJ9Bg",
    "diffPackageMap": null,
    "releaseMethod": "Upload",
    "uploadTime": 1506482500000,
    "originalLabel": "",
    "originalDeployment": "",
    "label": "v2",
    "releasedBy": "lisong2010@gmail.com",
    "metrics": {
      "active": 0,
      "downloaded": 0,
      "failed": 0,
      "installed": 0,
      "totalActive": 0
    }
  },
  {
    "description": "",
    "isDisabled": false,
    "isMandatory": false,
    "rollout": 100,
    "appVersion": "1.1",
    "packageHash": "6345ee86a09806e02122e5ddc2b214e0af501f31fc45ed46fc71b67ae9654510",
    "blobUrl": "http://owvyxjk6r.bkt.clouddn.com/Fo7JPCikEEYcErhz73TZfvSIcrs6",
    "size": 1033459,
    "manifestBlobUrl": "http://owvyxjk6r.bkt.clouddn.com/Fg70iO8AMunqf6ObhL3MW_WyaPna",
    "diffPackageMap": null,
    "releaseMethod": "Upload",
    "uploadTime": 1506481679000,
    "originalLabel": "",
    "originalDeployment": "",
    "label": "v1",
    "releasedBy": "lisong2010@gmail.com",
    "metrics": {
      "active": 0,
      "downloaded": 0,
      "failed": 0,
      "installed": 0,
      "totalActive": 0
    }
  }
]

**Comment by lisong** [comment]
是iOS没？是不是没有添加安全域

**Comment by andylidong** [comment]
sorry,是手机上挂了代理造成的
