### ISSUE TITLE
Unhandled rejection AbortError: Stream connection ended and command aborted.

### ISSUE THREAD

**Issue by erhutime** [lisong/code-push-server#97]
1-：执行code-push  release-react，本地服务器出错,
2-：浏览器输入：http://127.0.0.1:3000/updateCheck?deploymentKey=XJiabUpIS6p7GIlSBLvdlwEDxEae4ksvOXqog&appVersion=0.2.2&packageHash=&isCompanion=&label=&clientUniqueId=  返回错误信息一样
3-：查看本地目录文件storage文件夹里面，会生成一些其他文件夹，然后是具体的某个文件。

以上，请问如何解决。

**Comment by lisong** [comment]
错误信息是？是不是storageDir没有配置正确
