### ISSUE TITLE
An unknown error occurred

### ISSUE THREAD

**Issue by susieWang** [lisong/code-push-server#98]
code-push-server 和 code-push-demo-app 是在不同服务器上，按照http://blog.csdn.net/h254532699/article/details/54382162做了相应配置。
android 应用中启动后点击 Press for background sync 报错：An unknown error occurred.

**Comment by wuyunqiang** [comment]
请问你解决了嘛我也遇到这个问题。
可以显示更新提示框，点击更新。显示这个错误。
![codepushandroidrefused](https://user-images.githubusercontent.com/13480948/32591140-ed22bf7e-c558-11e7-8c80-a3e6f8459b93.png)

**Comment by lisong** [comment]
非https协议，需要在Info.list添加白名单
